// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: s2clientprotocol/debug.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebugGameState int32

const (
	DebugGameState_show_map      DebugGameState = 1
	DebugGameState_control_enemy DebugGameState = 2
	DebugGameState_food          DebugGameState = 3
	DebugGameState_free          DebugGameState = 4
	DebugGameState_all_resources DebugGameState = 5
	DebugGameState_god           DebugGameState = 6
	DebugGameState_minerals      DebugGameState = 7
	DebugGameState_gas           DebugGameState = 8
	DebugGameState_cooldown      DebugGameState = 9
	DebugGameState_tech_tree     DebugGameState = 10
	DebugGameState_upgrade       DebugGameState = 11
	DebugGameState_fast_build    DebugGameState = 12
)

// Enum value maps for DebugGameState.
var (
	DebugGameState_name = map[int32]string{
		1:  "show_map",
		2:  "control_enemy",
		3:  "food",
		4:  "free",
		5:  "all_resources",
		6:  "god",
		7:  "minerals",
		8:  "gas",
		9:  "cooldown",
		10: "tech_tree",
		11: "upgrade",
		12: "fast_build",
	}
	DebugGameState_value = map[string]int32{
		"show_map":      1,
		"control_enemy": 2,
		"food":          3,
		"free":          4,
		"all_resources": 5,
		"god":           6,
		"minerals":      7,
		"gas":           8,
		"cooldown":      9,
		"tech_tree":     10,
		"upgrade":       11,
		"fast_build":    12,
	}
)

func (x DebugGameState) Enum() *DebugGameState {
	p := new(DebugGameState)
	*p = x
	return p
}

func (x DebugGameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugGameState) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_debug_proto_enumTypes[0].Descriptor()
}

func (DebugGameState) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_debug_proto_enumTypes[0]
}

func (x DebugGameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DebugGameState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DebugGameState(num)
	return nil
}

// Deprecated: Use DebugGameState.Descriptor instead.
func (DebugGameState) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{0}
}

type DebugTestProcess_Test int32

const (
	DebugTestProcess_hang  DebugTestProcess_Test = 1
	DebugTestProcess_crash DebugTestProcess_Test = 2
	DebugTestProcess_exit  DebugTestProcess_Test = 3
)

// Enum value maps for DebugTestProcess_Test.
var (
	DebugTestProcess_Test_name = map[int32]string{
		1: "hang",
		2: "crash",
		3: "exit",
	}
	DebugTestProcess_Test_value = map[string]int32{
		"hang":  1,
		"crash": 2,
		"exit":  3,
	}
)

func (x DebugTestProcess_Test) Enum() *DebugTestProcess_Test {
	p := new(DebugTestProcess_Test)
	*p = x
	return p
}

func (x DebugTestProcess_Test) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugTestProcess_Test) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_debug_proto_enumTypes[1].Descriptor()
}

func (DebugTestProcess_Test) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_debug_proto_enumTypes[1]
}

func (x DebugTestProcess_Test) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DebugTestProcess_Test) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DebugTestProcess_Test(num)
	return nil
}

// Deprecated: Use DebugTestProcess_Test.Descriptor instead.
func (DebugTestProcess_Test) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{10, 0}
}

type DebugEndGame_EndResult int32

const (
	DebugEndGame_Surrender      DebugEndGame_EndResult = 1 // Default if nothing is set. The current player admits defeat.
	DebugEndGame_DeclareVictory DebugEndGame_EndResult = 2
)

// Enum value maps for DebugEndGame_EndResult.
var (
	DebugEndGame_EndResult_name = map[int32]string{
		1: "Surrender",
		2: "DeclareVictory",
	}
	DebugEndGame_EndResult_value = map[string]int32{
		"Surrender":      1,
		"DeclareVictory": 2,
	}
)

func (x DebugEndGame_EndResult) Enum() *DebugEndGame_EndResult {
	p := new(DebugEndGame_EndResult)
	*p = x
	return p
}

func (x DebugEndGame_EndResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugEndGame_EndResult) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_debug_proto_enumTypes[2].Descriptor()
}

func (DebugEndGame_EndResult) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_debug_proto_enumTypes[2]
}

func (x DebugEndGame_EndResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DebugEndGame_EndResult) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DebugEndGame_EndResult(num)
	return nil
}

// Deprecated: Use DebugEndGame_EndResult.Descriptor instead.
func (DebugEndGame_EndResult) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{12, 0}
}

type DebugSetUnitValue_UnitValue int32

const (
	DebugSetUnitValue_Energy  DebugSetUnitValue_UnitValue = 1
	DebugSetUnitValue_Life    DebugSetUnitValue_UnitValue = 2
	DebugSetUnitValue_Shields DebugSetUnitValue_UnitValue = 3
)

// Enum value maps for DebugSetUnitValue_UnitValue.
var (
	DebugSetUnitValue_UnitValue_name = map[int32]string{
		1: "Energy",
		2: "Life",
		3: "Shields",
	}
	DebugSetUnitValue_UnitValue_value = map[string]int32{
		"Energy":  1,
		"Life":    2,
		"Shields": 3,
	}
)

func (x DebugSetUnitValue_UnitValue) Enum() *DebugSetUnitValue_UnitValue {
	p := new(DebugSetUnitValue_UnitValue)
	*p = x
	return p
}

func (x DebugSetUnitValue_UnitValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DebugSetUnitValue_UnitValue) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_debug_proto_enumTypes[3].Descriptor()
}

func (DebugSetUnitValue_UnitValue) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_debug_proto_enumTypes[3]
}

func (x DebugSetUnitValue_UnitValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DebugSetUnitValue_UnitValue) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DebugSetUnitValue_UnitValue(num)
	return nil
}

// Deprecated: Use DebugSetUnitValue_UnitValue.Descriptor instead.
func (DebugSetUnitValue_UnitValue) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{13, 0}
}

// Issue various useful commands to the game engine.
type DebugCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*DebugCommand_Draw
	//	*DebugCommand_GameState
	//	*DebugCommand_CreateUnit
	//	*DebugCommand_KillUnit
	//	*DebugCommand_TestProcess
	//	*DebugCommand_Score
	//	*DebugCommand_EndGame
	//	*DebugCommand_UnitValue
	Command       isDebugCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugCommand) Reset() {
	*x = DebugCommand{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugCommand) ProtoMessage() {}

func (x *DebugCommand) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugCommand.ProtoReflect.Descriptor instead.
func (*DebugCommand) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{0}
}

func (x *DebugCommand) GetCommand() isDebugCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DebugCommand) GetDraw() *DebugDraw {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_Draw); ok {
			return x.Draw
		}
	}
	return nil
}

func (x *DebugCommand) GetGameState() DebugGameState {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_GameState); ok {
			return x.GameState
		}
	}
	return DebugGameState_show_map
}

func (x *DebugCommand) GetCreateUnit() *DebugCreateUnit {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_CreateUnit); ok {
			return x.CreateUnit
		}
	}
	return nil
}

func (x *DebugCommand) GetKillUnit() *DebugKillUnit {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_KillUnit); ok {
			return x.KillUnit
		}
	}
	return nil
}

func (x *DebugCommand) GetTestProcess() *DebugTestProcess {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_TestProcess); ok {
			return x.TestProcess
		}
	}
	return nil
}

func (x *DebugCommand) GetScore() *DebugSetScore {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_Score); ok {
			return x.Score
		}
	}
	return nil
}

func (x *DebugCommand) GetEndGame() *DebugEndGame {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_EndGame); ok {
			return x.EndGame
		}
	}
	return nil
}

func (x *DebugCommand) GetUnitValue() *DebugSetUnitValue {
	if x != nil {
		if x, ok := x.Command.(*DebugCommand_UnitValue); ok {
			return x.UnitValue
		}
	}
	return nil
}

type isDebugCommand_Command interface {
	isDebugCommand_Command()
}

type DebugCommand_Draw struct {
	Draw *DebugDraw `protobuf:"bytes,1,opt,name=draw,oneof"`
}

type DebugCommand_GameState struct {
	GameState DebugGameState `protobuf:"varint,2,opt,name=game_state,json=gameState,enum=SC2APIProtocol.DebugGameState,oneof"`
}

type DebugCommand_CreateUnit struct {
	CreateUnit *DebugCreateUnit `protobuf:"bytes,3,opt,name=create_unit,json=createUnit,oneof"`
}

type DebugCommand_KillUnit struct {
	KillUnit *DebugKillUnit `protobuf:"bytes,4,opt,name=kill_unit,json=killUnit,oneof"`
}

type DebugCommand_TestProcess struct {
	TestProcess *DebugTestProcess `protobuf:"bytes,5,opt,name=test_process,json=testProcess,oneof"`
}

type DebugCommand_Score struct {
	Score *DebugSetScore `protobuf:"bytes,6,opt,name=score,oneof"` // Useful only for single-player "curriculum" maps.
}

type DebugCommand_EndGame struct {
	EndGame *DebugEndGame `protobuf:"bytes,7,opt,name=end_game,json=endGame,oneof"`
}

type DebugCommand_UnitValue struct {
	UnitValue *DebugSetUnitValue `protobuf:"bytes,8,opt,name=unit_value,json=unitValue,oneof"`
}

func (*DebugCommand_Draw) isDebugCommand_Command() {}

func (*DebugCommand_GameState) isDebugCommand_Command() {}

func (*DebugCommand_CreateUnit) isDebugCommand_Command() {}

func (*DebugCommand_KillUnit) isDebugCommand_Command() {}

func (*DebugCommand_TestProcess) isDebugCommand_Command() {}

func (*DebugCommand_Score) isDebugCommand_Command() {}

func (*DebugCommand_EndGame) isDebugCommand_Command() {}

func (*DebugCommand_UnitValue) isDebugCommand_Command() {}

type DebugDraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []*DebugText           `protobuf:"bytes,1,rep,name=text" json:"text,omitempty"`
	Lines         []*DebugLine           `protobuf:"bytes,2,rep,name=lines" json:"lines,omitempty"`
	Boxes         []*DebugBox            `protobuf:"bytes,3,rep,name=boxes" json:"boxes,omitempty"`
	Spheres       []*DebugSphere         `protobuf:"bytes,4,rep,name=spheres" json:"spheres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugDraw) Reset() {
	*x = DebugDraw{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugDraw) ProtoMessage() {}

func (x *DebugDraw) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugDraw.ProtoReflect.Descriptor instead.
func (*DebugDraw) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{1}
}

func (x *DebugDraw) GetText() []*DebugText {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *DebugDraw) GetLines() []*DebugLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *DebugDraw) GetBoxes() []*DebugBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

func (x *DebugDraw) GetSpheres() []*DebugSphere {
	if x != nil {
		return x.Spheres
	}
	return nil
}

type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P0            *Point                 `protobuf:"bytes,1,opt,name=p0" json:"p0,omitempty"`
	P1            *Point                 `protobuf:"bytes,2,opt,name=p1" json:"p1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{2}
}

func (x *Line) GetP0() *Point {
	if x != nil {
		return x.P0
	}
	return nil
}

func (x *Line) GetP1() *Point {
	if x != nil {
		return x.P1
	}
	return nil
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *uint32                `protobuf:"varint,1,opt,name=r" json:"r,omitempty"`
	G             *uint32                `protobuf:"varint,2,opt,name=g" json:"g,omitempty"`
	B             *uint32                `protobuf:"varint,3,opt,name=b" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{3}
}

func (x *Color) GetR() uint32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

// Display debug text on screen.
type DebugText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`                               // Text to display.
	VirtualPos    *Point                 `protobuf:"bytes,3,opt,name=virtual_pos,json=virtualPos" json:"virtual_pos,omitempty"` // Virtualized position in 2D (the screen is 0..1, 0..1 for any resolution).
	WorldPos      *Point                 `protobuf:"bytes,4,opt,name=world_pos,json=worldPos" json:"world_pos,omitempty"`       // Position in the world.
	Size          *uint32                `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`                              // Pixel height of the text. Defaults to 8px.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugText) Reset() {
	*x = DebugText{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugText) ProtoMessage() {}

func (x *DebugText) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugText.ProtoReflect.Descriptor instead.
func (*DebugText) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{4}
}

func (x *DebugText) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *DebugText) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *DebugText) GetVirtualPos() *Point {
	if x != nil {
		return x.VirtualPos
	}
	return nil
}

func (x *DebugText) GetWorldPos() *Point {
	if x != nil {
		return x.WorldPos
	}
	return nil
}

func (x *DebugText) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

// Display debug lines on screen.
type DebugLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	Line          *Line                  `protobuf:"bytes,2,opt,name=line" json:"line,omitempty"` // World space line.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugLine) Reset() {
	*x = DebugLine{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugLine) ProtoMessage() {}

func (x *DebugLine) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugLine.ProtoReflect.Descriptor instead.
func (*DebugLine) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{5}
}

func (x *DebugLine) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *DebugLine) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

// Display debug boxes on screen.
type DebugBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	Min           *Point                 `protobuf:"bytes,2,opt,name=min" json:"min,omitempty"`
	Max           *Point                 `protobuf:"bytes,3,opt,name=max" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugBox) Reset() {
	*x = DebugBox{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugBox) ProtoMessage() {}

func (x *DebugBox) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugBox.ProtoReflect.Descriptor instead.
func (*DebugBox) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{6}
}

func (x *DebugBox) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *DebugBox) GetMin() *Point {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *DebugBox) GetMax() *Point {
	if x != nil {
		return x.Max
	}
	return nil
}

// Display debug spheres on screen.
type DebugSphere struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	P             *Point                 `protobuf:"bytes,2,opt,name=p" json:"p,omitempty"`
	R             *float32               `protobuf:"fixed32,3,opt,name=r" json:"r,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugSphere) Reset() {
	*x = DebugSphere{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugSphere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugSphere) ProtoMessage() {}

func (x *DebugSphere) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugSphere.ProtoReflect.Descriptor instead.
func (*DebugSphere) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{7}
}

func (x *DebugSphere) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *DebugSphere) GetP() *Point {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *DebugSphere) GetR() float32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

type DebugCreateUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitType      *uint32                `protobuf:"varint,1,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	Owner         *int32                 `protobuf:"varint,2,opt,name=owner" json:"owner,omitempty"`
	Pos           *Point2D               `protobuf:"bytes,3,opt,name=pos" json:"pos,omitempty"`
	Quantity      *uint32                `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugCreateUnit) Reset() {
	*x = DebugCreateUnit{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugCreateUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugCreateUnit) ProtoMessage() {}

func (x *DebugCreateUnit) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugCreateUnit.ProtoReflect.Descriptor instead.
func (*DebugCreateUnit) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{8}
}

func (x *DebugCreateUnit) GetUnitType() uint32 {
	if x != nil && x.UnitType != nil {
		return *x.UnitType
	}
	return 0
}

func (x *DebugCreateUnit) GetOwner() int32 {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return 0
}

func (x *DebugCreateUnit) GetPos() *Point2D {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *DebugCreateUnit) GetQuantity() uint32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

type DebugKillUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []uint64               `protobuf:"varint,1,rep,name=tag" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugKillUnit) Reset() {
	*x = DebugKillUnit{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugKillUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugKillUnit) ProtoMessage() {}

func (x *DebugKillUnit) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugKillUnit.ProtoReflect.Descriptor instead.
func (*DebugKillUnit) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{9}
}

func (x *DebugKillUnit) GetTag() []uint64 {
	if x != nil {
		return x.Tag
	}
	return nil
}

type DebugTestProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          *DebugTestProcess_Test `protobuf:"varint,1,opt,name=test,enum=SC2APIProtocol.DebugTestProcess_Test" json:"test,omitempty"`
	DelayMs       *int32                 `protobuf:"varint,2,opt,name=delay_ms,json=delayMs" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugTestProcess) Reset() {
	*x = DebugTestProcess{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugTestProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugTestProcess) ProtoMessage() {}

func (x *DebugTestProcess) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugTestProcess.ProtoReflect.Descriptor instead.
func (*DebugTestProcess) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{10}
}

func (x *DebugTestProcess) GetTest() DebugTestProcess_Test {
	if x != nil && x.Test != nil {
		return *x.Test
	}
	return DebugTestProcess_hang
}

func (x *DebugTestProcess) GetDelayMs() int32 {
	if x != nil && x.DelayMs != nil {
		return *x.DelayMs
	}
	return 0
}

type DebugSetScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *float32               `protobuf:"fixed32,1,opt,name=score" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugSetScore) Reset() {
	*x = DebugSetScore{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugSetScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugSetScore) ProtoMessage() {}

func (x *DebugSetScore) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugSetScore.ProtoReflect.Descriptor instead.
func (*DebugSetScore) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{11}
}

func (x *DebugSetScore) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type DebugEndGame struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EndResult     *DebugEndGame_EndResult `protobuf:"varint,1,opt,name=end_result,json=endResult,enum=SC2APIProtocol.DebugEndGame_EndResult" json:"end_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugEndGame) Reset() {
	*x = DebugEndGame{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugEndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugEndGame) ProtoMessage() {}

func (x *DebugEndGame) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugEndGame.ProtoReflect.Descriptor instead.
func (*DebugEndGame) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{12}
}

func (x *DebugEndGame) GetEndResult() DebugEndGame_EndResult {
	if x != nil && x.EndResult != nil {
		return *x.EndResult
	}
	return DebugEndGame_Surrender
}

type DebugSetUnitValue struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	UnitValue     *DebugSetUnitValue_UnitValue `protobuf:"varint,1,opt,name=unit_value,json=unitValue,enum=SC2APIProtocol.DebugSetUnitValue_UnitValue" json:"unit_value,omitempty"`
	Value         *float32                     `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
	UnitTag       *uint64                      `protobuf:"varint,3,opt,name=unit_tag,json=unitTag" json:"unit_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugSetUnitValue) Reset() {
	*x = DebugSetUnitValue{}
	mi := &file_s2clientprotocol_debug_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugSetUnitValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugSetUnitValue) ProtoMessage() {}

func (x *DebugSetUnitValue) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_debug_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugSetUnitValue.ProtoReflect.Descriptor instead.
func (*DebugSetUnitValue) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_debug_proto_rawDescGZIP(), []int{13}
}

func (x *DebugSetUnitValue) GetUnitValue() DebugSetUnitValue_UnitValue {
	if x != nil && x.UnitValue != nil {
		return *x.UnitValue
	}
	return DebugSetUnitValue_Energy
}

func (x *DebugSetUnitValue) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *DebugSetUnitValue) GetUnitTag() uint64 {
	if x != nil && x.UnitTag != nil {
		return *x.UnitTag
	}
	return 0
}

var File_s2clientprotocol_debug_proto protoreflect.FileDescriptor

const file_s2clientprotocol_debug_proto_rawDesc = "" +
	"\n" +
	"\x1cs2clientprotocol/debug.proto\x12\x0eSC2APIProtocol\x1a\x1ds2clientprotocol/common.proto\"\x8a\x04\n" +
	"\fDebugCommand\x12/\n" +
	"\x04draw\x18\x01 \x01(\v2\x19.SC2APIProtocol.DebugDrawH\x00R\x04draw\x12?\n" +
	"\n" +
	"game_state\x18\x02 \x01(\x0e2\x1e.SC2APIProtocol.DebugGameStateH\x00R\tgameState\x12B\n" +
	"\vcreate_unit\x18\x03 \x01(\v2\x1f.SC2APIProtocol.DebugCreateUnitH\x00R\n" +
	"createUnit\x12<\n" +
	"\tkill_unit\x18\x04 \x01(\v2\x1d.SC2APIProtocol.DebugKillUnitH\x00R\bkillUnit\x12E\n" +
	"\ftest_process\x18\x05 \x01(\v2 .SC2APIProtocol.DebugTestProcessH\x00R\vtestProcess\x125\n" +
	"\x05score\x18\x06 \x01(\v2\x1d.SC2APIProtocol.DebugSetScoreH\x00R\x05score\x129\n" +
	"\bend_game\x18\a \x01(\v2\x1c.SC2APIProtocol.DebugEndGameH\x00R\aendGame\x12B\n" +
	"\n" +
	"unit_value\x18\b \x01(\v2!.SC2APIProtocol.DebugSetUnitValueH\x00R\tunitValueB\t\n" +
	"\acommand\"\xd2\x01\n" +
	"\tDebugDraw\x12-\n" +
	"\x04text\x18\x01 \x03(\v2\x19.SC2APIProtocol.DebugTextR\x04text\x12/\n" +
	"\x05lines\x18\x02 \x03(\v2\x19.SC2APIProtocol.DebugLineR\x05lines\x12.\n" +
	"\x05boxes\x18\x03 \x03(\v2\x18.SC2APIProtocol.DebugBoxR\x05boxes\x125\n" +
	"\aspheres\x18\x04 \x03(\v2\x1b.SC2APIProtocol.DebugSphereR\aspheres\"T\n" +
	"\x04Line\x12%\n" +
	"\x02p0\x18\x01 \x01(\v2\x15.SC2APIProtocol.PointR\x02p0\x12%\n" +
	"\x02p1\x18\x02 \x01(\v2\x15.SC2APIProtocol.PointR\x02p1\"1\n" +
	"\x05Color\x12\f\n" +
	"\x01r\x18\x01 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\rR\x01b\"\xcc\x01\n" +
	"\tDebugText\x12+\n" +
	"\x05color\x18\x01 \x01(\v2\x15.SC2APIProtocol.ColorR\x05color\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x126\n" +
	"\vvirtual_pos\x18\x03 \x01(\v2\x15.SC2APIProtocol.PointR\n" +
	"virtualPos\x122\n" +
	"\tworld_pos\x18\x04 \x01(\v2\x15.SC2APIProtocol.PointR\bworldPos\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\"b\n" +
	"\tDebugLine\x12+\n" +
	"\x05color\x18\x01 \x01(\v2\x15.SC2APIProtocol.ColorR\x05color\x12(\n" +
	"\x04line\x18\x02 \x01(\v2\x14.SC2APIProtocol.LineR\x04line\"\x89\x01\n" +
	"\bDebugBox\x12+\n" +
	"\x05color\x18\x01 \x01(\v2\x15.SC2APIProtocol.ColorR\x05color\x12'\n" +
	"\x03min\x18\x02 \x01(\v2\x15.SC2APIProtocol.PointR\x03min\x12'\n" +
	"\x03max\x18\x03 \x01(\v2\x15.SC2APIProtocol.PointR\x03max\"m\n" +
	"\vDebugSphere\x12+\n" +
	"\x05color\x18\x01 \x01(\v2\x15.SC2APIProtocol.ColorR\x05color\x12#\n" +
	"\x01p\x18\x02 \x01(\v2\x15.SC2APIProtocol.PointR\x01p\x12\f\n" +
	"\x01r\x18\x03 \x01(\x02R\x01r\"\x8b\x01\n" +
	"\x0fDebugCreateUnit\x12\x1b\n" +
	"\tunit_type\x18\x01 \x01(\rR\bunitType\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\x05R\x05owner\x12)\n" +
	"\x03pos\x18\x03 \x01(\v2\x17.SC2APIProtocol.Point2DR\x03pos\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\"!\n" +
	"\rDebugKillUnit\x12\x10\n" +
	"\x03tag\x18\x01 \x03(\x04R\x03tag\"\x8f\x01\n" +
	"\x10DebugTestProcess\x129\n" +
	"\x04test\x18\x01 \x01(\x0e2%.SC2APIProtocol.DebugTestProcess.TestR\x04test\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"%\n" +
	"\x04Test\x12\b\n" +
	"\x04hang\x10\x01\x12\t\n" +
	"\x05crash\x10\x02\x12\b\n" +
	"\x04exit\x10\x03\"%\n" +
	"\rDebugSetScore\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\"\x85\x01\n" +
	"\fDebugEndGame\x12E\n" +
	"\n" +
	"end_result\x18\x01 \x01(\x0e2&.SC2APIProtocol.DebugEndGame.EndResultR\tendResult\".\n" +
	"\tEndResult\x12\r\n" +
	"\tSurrender\x10\x01\x12\x12\n" +
	"\x0eDeclareVictory\x10\x02\"\xc0\x01\n" +
	"\x11DebugSetUnitValue\x12J\n" +
	"\n" +
	"unit_value\x18\x01 \x01(\x0e2+.SC2APIProtocol.DebugSetUnitValue.UnitValueR\tunitValue\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x19\n" +
	"\bunit_tag\x18\x03 \x01(\x04R\aunitTag\".\n" +
	"\tUnitValue\x12\n" +
	"\n" +
	"\x06Energy\x10\x01\x12\b\n" +
	"\x04Life\x10\x02\x12\v\n" +
	"\aShields\x10\x03*\xb2\x01\n" +
	"\x0eDebugGameState\x12\f\n" +
	"\bshow_map\x10\x01\x12\x11\n" +
	"\rcontrol_enemy\x10\x02\x12\b\n" +
	"\x04food\x10\x03\x12\b\n" +
	"\x04free\x10\x04\x12\x11\n" +
	"\rall_resources\x10\x05\x12\a\n" +
	"\x03god\x10\x06\x12\f\n" +
	"\bminerals\x10\a\x12\a\n" +
	"\x03gas\x10\b\x12\f\n" +
	"\bcooldown\x10\t\x12\r\n" +
	"\ttech_tree\x10\n" +
	"\x12\v\n" +
	"\aupgrade\x10\v\x12\x0e\n" +
	"\n" +
	"fast_build\x10\f"

var (
	file_s2clientprotocol_debug_proto_rawDescOnce sync.Once
	file_s2clientprotocol_debug_proto_rawDescData []byte
)

func file_s2clientprotocol_debug_proto_rawDescGZIP() []byte {
	file_s2clientprotocol_debug_proto_rawDescOnce.Do(func() {
		file_s2clientprotocol_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2clientprotocol_debug_proto_rawDesc), len(file_s2clientprotocol_debug_proto_rawDesc)))
	})
	return file_s2clientprotocol_debug_proto_rawDescData
}

var file_s2clientprotocol_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_s2clientprotocol_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_s2clientprotocol_debug_proto_goTypes = []any{
	(DebugGameState)(0),              // 0: SC2APIProtocol.DebugGameState
	(DebugTestProcess_Test)(0),       // 1: SC2APIProtocol.DebugTestProcess.Test
	(DebugEndGame_EndResult)(0),      // 2: SC2APIProtocol.DebugEndGame.EndResult
	(DebugSetUnitValue_UnitValue)(0), // 3: SC2APIProtocol.DebugSetUnitValue.UnitValue
	(*DebugCommand)(nil),             // 4: SC2APIProtocol.DebugCommand
	(*DebugDraw)(nil),                // 5: SC2APIProtocol.DebugDraw
	(*Line)(nil),                     // 6: SC2APIProtocol.Line
	(*Color)(nil),                    // 7: SC2APIProtocol.Color
	(*DebugText)(nil),                // 8: SC2APIProtocol.DebugText
	(*DebugLine)(nil),                // 9: SC2APIProtocol.DebugLine
	(*DebugBox)(nil),                 // 10: SC2APIProtocol.DebugBox
	(*DebugSphere)(nil),              // 11: SC2APIProtocol.DebugSphere
	(*DebugCreateUnit)(nil),          // 12: SC2APIProtocol.DebugCreateUnit
	(*DebugKillUnit)(nil),            // 13: SC2APIProtocol.DebugKillUnit
	(*DebugTestProcess)(nil),         // 14: SC2APIProtocol.DebugTestProcess
	(*DebugSetScore)(nil),            // 15: SC2APIProtocol.DebugSetScore
	(*DebugEndGame)(nil),             // 16: SC2APIProtocol.DebugEndGame
	(*DebugSetUnitValue)(nil),        // 17: SC2APIProtocol.DebugSetUnitValue
	(*Point)(nil),                    // 18: SC2APIProtocol.Point
	(*Point2D)(nil),                  // 19: SC2APIProtocol.Point2D
}
var file_s2clientprotocol_debug_proto_depIdxs = []int32{
	5,  // 0: SC2APIProtocol.DebugCommand.draw:type_name -> SC2APIProtocol.DebugDraw
	0,  // 1: SC2APIProtocol.DebugCommand.game_state:type_name -> SC2APIProtocol.DebugGameState
	12, // 2: SC2APIProtocol.DebugCommand.create_unit:type_name -> SC2APIProtocol.DebugCreateUnit
	13, // 3: SC2APIProtocol.DebugCommand.kill_unit:type_name -> SC2APIProtocol.DebugKillUnit
	14, // 4: SC2APIProtocol.DebugCommand.test_process:type_name -> SC2APIProtocol.DebugTestProcess
	15, // 5: SC2APIProtocol.DebugCommand.score:type_name -> SC2APIProtocol.DebugSetScore
	16, // 6: SC2APIProtocol.DebugCommand.end_game:type_name -> SC2APIProtocol.DebugEndGame
	17, // 7: SC2APIProtocol.DebugCommand.unit_value:type_name -> SC2APIProtocol.DebugSetUnitValue
	8,  // 8: SC2APIProtocol.DebugDraw.text:type_name -> SC2APIProtocol.DebugText
	9,  // 9: SC2APIProtocol.DebugDraw.lines:type_name -> SC2APIProtocol.DebugLine
	10, // 10: SC2APIProtocol.DebugDraw.boxes:type_name -> SC2APIProtocol.DebugBox
	11, // 11: SC2APIProtocol.DebugDraw.spheres:type_name -> SC2APIProtocol.DebugSphere
	18, // 12: SC2APIProtocol.Line.p0:type_name -> SC2APIProtocol.Point
	18, // 13: SC2APIProtocol.Line.p1:type_name -> SC2APIProtocol.Point
	7,  // 14: SC2APIProtocol.DebugText.color:type_name -> SC2APIProtocol.Color
	18, // 15: SC2APIProtocol.DebugText.virtual_pos:type_name -> SC2APIProtocol.Point
	18, // 16: SC2APIProtocol.DebugText.world_pos:type_name -> SC2APIProtocol.Point
	7,  // 17: SC2APIProtocol.DebugLine.color:type_name -> SC2APIProtocol.Color
	6,  // 18: SC2APIProtocol.DebugLine.line:type_name -> SC2APIProtocol.Line
	7,  // 19: SC2APIProtocol.DebugBox.color:type_name -> SC2APIProtocol.Color
	18, // 20: SC2APIProtocol.DebugBox.min:type_name -> SC2APIProtocol.Point
	18, // 21: SC2APIProtocol.DebugBox.max:type_name -> SC2APIProtocol.Point
	7,  // 22: SC2APIProtocol.DebugSphere.color:type_name -> SC2APIProtocol.Color
	18, // 23: SC2APIProtocol.DebugSphere.p:type_name -> SC2APIProtocol.Point
	19, // 24: SC2APIProtocol.DebugCreateUnit.pos:type_name -> SC2APIProtocol.Point2D
	1,  // 25: SC2APIProtocol.DebugTestProcess.test:type_name -> SC2APIProtocol.DebugTestProcess.Test
	2,  // 26: SC2APIProtocol.DebugEndGame.end_result:type_name -> SC2APIProtocol.DebugEndGame.EndResult
	3,  // 27: SC2APIProtocol.DebugSetUnitValue.unit_value:type_name -> SC2APIProtocol.DebugSetUnitValue.UnitValue
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_s2clientprotocol_debug_proto_init() }
func file_s2clientprotocol_debug_proto_init() {
	if File_s2clientprotocol_debug_proto != nil {
		return
	}
	file_s2clientprotocol_common_proto_init()
	file_s2clientprotocol_debug_proto_msgTypes[0].OneofWrappers = []any{
		(*DebugCommand_Draw)(nil),
		(*DebugCommand_GameState)(nil),
		(*DebugCommand_CreateUnit)(nil),
		(*DebugCommand_KillUnit)(nil),
		(*DebugCommand_TestProcess)(nil),
		(*DebugCommand_Score)(nil),
		(*DebugCommand_EndGame)(nil),
		(*DebugCommand_UnitValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2clientprotocol_debug_proto_rawDesc), len(file_s2clientprotocol_debug_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2clientprotocol_debug_proto_goTypes,
		DependencyIndexes: file_s2clientprotocol_debug_proto_depIdxs,
		EnumInfos:         file_s2clientprotocol_debug_proto_enumTypes,
		MessageInfos:      file_s2clientprotocol_debug_proto_msgTypes,
	}.Build()
	File_s2clientprotocol_debug_proto = out.File
	file_s2clientprotocol_debug_proto_goTypes = nil
	file_s2clientprotocol_debug_proto_depIdxs = nil
}
