// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: s2clientprotocol/raw.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisplayType int32

const (
	DisplayType_Visible     DisplayType = 1 // Fully visible
	DisplayType_Snapshot    DisplayType = 2 // Dimmed version of unit left behind after entering fog of war
	DisplayType_Hidden      DisplayType = 3 // Fully hidden
	DisplayType_Placeholder DisplayType = 4 // Building that hasn't started construction.
)

// Enum value maps for DisplayType.
var (
	DisplayType_name = map[int32]string{
		1: "Visible",
		2: "Snapshot",
		3: "Hidden",
		4: "Placeholder",
	}
	DisplayType_value = map[string]int32{
		"Visible":     1,
		"Snapshot":    2,
		"Hidden":      3,
		"Placeholder": 4,
	}
)

func (x DisplayType) Enum() *DisplayType {
	p := new(DisplayType)
	*p = x
	return p
}

func (x DisplayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisplayType) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_raw_proto_enumTypes[0].Descriptor()
}

func (DisplayType) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_raw_proto_enumTypes[0]
}

func (x DisplayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DisplayType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DisplayType(num)
	return nil
}

// Deprecated: Use DisplayType.Descriptor instead.
func (DisplayType) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{0}
}

type Alliance int32

const (
	Alliance_Self    Alliance = 1
	Alliance_Ally    Alliance = 2
	Alliance_Neutral Alliance = 3
	Alliance_Enemy   Alliance = 4
)

// Enum value maps for Alliance.
var (
	Alliance_name = map[int32]string{
		1: "Self",
		2: "Ally",
		3: "Neutral",
		4: "Enemy",
	}
	Alliance_value = map[string]int32{
		"Self":    1,
		"Ally":    2,
		"Neutral": 3,
		"Enemy":   4,
	}
)

func (x Alliance) Enum() *Alliance {
	p := new(Alliance)
	*p = x
	return p
}

func (x Alliance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alliance) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_raw_proto_enumTypes[1].Descriptor()
}

func (Alliance) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_raw_proto_enumTypes[1]
}

func (x Alliance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Alliance) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Alliance(num)
	return nil
}

// Deprecated: Use Alliance.Descriptor instead.
func (Alliance) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{1}
}

type CloakState int32

const (
	CloakState_CloakedUnknown  CloakState = 0 // Under the fog, so unknown whether it's cloaked or not.
	CloakState_Cloaked         CloakState = 1
	CloakState_CloakedDetected CloakState = 2
	CloakState_NotCloaked      CloakState = 3
	CloakState_CloakedAllied   CloakState = 4
)

// Enum value maps for CloakState.
var (
	CloakState_name = map[int32]string{
		0: "CloakedUnknown",
		1: "Cloaked",
		2: "CloakedDetected",
		3: "NotCloaked",
		4: "CloakedAllied",
	}
	CloakState_value = map[string]int32{
		"CloakedUnknown":  0,
		"Cloaked":         1,
		"CloakedDetected": 2,
		"NotCloaked":      3,
		"CloakedAllied":   4,
	}
)

func (x CloakState) Enum() *CloakState {
	p := new(CloakState)
	*p = x
	return p
}

func (x CloakState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloakState) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_raw_proto_enumTypes[2].Descriptor()
}

func (CloakState) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_raw_proto_enumTypes[2]
}

func (x CloakState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CloakState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CloakState(num)
	return nil
}

// Deprecated: Use CloakState.Descriptor instead.
func (CloakState) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{2}
}

type StartRaw struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MapSize        *Size2DI               `protobuf:"bytes,1,opt,name=map_size,json=mapSize" json:"map_size,omitempty"`                      // Width and height of the map.
	PathingGrid    *ImageData             `protobuf:"bytes,2,opt,name=pathing_grid,json=pathingGrid" json:"pathing_grid,omitempty"`          // 1 bit bitmap of the pathing grid.
	TerrainHeight  *ImageData             `protobuf:"bytes,3,opt,name=terrain_height,json=terrainHeight" json:"terrain_height,omitempty"`    // 1 byte bitmap of the terrain height.
	PlacementGrid  *ImageData             `protobuf:"bytes,4,opt,name=placement_grid,json=placementGrid" json:"placement_grid,omitempty"`    // 1 bit bitmap of the building placement grid.
	PlayableArea   *RectangleI            `protobuf:"bytes,5,opt,name=playable_area,json=playableArea" json:"playable_area,omitempty"`       // The playable cells.
	StartLocations []*Point2D             `protobuf:"bytes,6,rep,name=start_locations,json=startLocations" json:"start_locations,omitempty"` // Possible start locations for players.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartRaw) Reset() {
	*x = StartRaw{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRaw) ProtoMessage() {}

func (x *StartRaw) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRaw.ProtoReflect.Descriptor instead.
func (*StartRaw) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{0}
}

func (x *StartRaw) GetMapSize() *Size2DI {
	if x != nil {
		return x.MapSize
	}
	return nil
}

func (x *StartRaw) GetPathingGrid() *ImageData {
	if x != nil {
		return x.PathingGrid
	}
	return nil
}

func (x *StartRaw) GetTerrainHeight() *ImageData {
	if x != nil {
		return x.TerrainHeight
	}
	return nil
}

func (x *StartRaw) GetPlacementGrid() *ImageData {
	if x != nil {
		return x.PlacementGrid
	}
	return nil
}

func (x *StartRaw) GetPlayableArea() *RectangleI {
	if x != nil {
		return x.PlayableArea
	}
	return nil
}

func (x *StartRaw) GetStartLocations() []*Point2D {
	if x != nil {
		return x.StartLocations
	}
	return nil
}

type ObservationRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRaw             `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	Units         []*Unit                `protobuf:"bytes,2,rep,name=units" json:"units,omitempty"`
	MapState      *MapState              `protobuf:"bytes,3,opt,name=map_state,json=mapState" json:"map_state,omitempty"` // Fog of war, creep and so on. Board stuff that changes per frame.
	Event         *Event                 `protobuf:"bytes,4,opt,name=event" json:"event,omitempty"`
	Effects       []*Effect              `protobuf:"bytes,5,rep,name=effects" json:"effects,omitempty"`
	Radar         []*RadarRing           `protobuf:"bytes,6,rep,name=radar" json:"radar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationRaw) Reset() {
	*x = ObservationRaw{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationRaw) ProtoMessage() {}

func (x *ObservationRaw) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationRaw.ProtoReflect.Descriptor instead.
func (*ObservationRaw) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{1}
}

func (x *ObservationRaw) GetPlayer() *PlayerRaw {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ObservationRaw) GetUnits() []*Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *ObservationRaw) GetMapState() *MapState {
	if x != nil {
		return x.MapState
	}
	return nil
}

func (x *ObservationRaw) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ObservationRaw) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ObservationRaw) GetRadar() []*RadarRing {
	if x != nil {
		return x.Radar
	}
	return nil
}

type RadarRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Point                 `protobuf:"bytes,1,opt,name=pos" json:"pos,omitempty"`
	Radius        *float32               `protobuf:"fixed32,2,opt,name=radius" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarRing) Reset() {
	*x = RadarRing{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarRing) ProtoMessage() {}

func (x *RadarRing) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarRing.ProtoReflect.Descriptor instead.
func (*RadarRing) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{2}
}

func (x *RadarRing) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *RadarRing) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

type PowerSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Point                 `protobuf:"bytes,1,opt,name=pos" json:"pos,omitempty"`
	Radius        *float32               `protobuf:"fixed32,2,opt,name=radius" json:"radius,omitempty"`
	Tag           *uint64                `protobuf:"varint,3,opt,name=tag" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerSource) Reset() {
	*x = PowerSource{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerSource) ProtoMessage() {}

func (x *PowerSource) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerSource.ProtoReflect.Descriptor instead.
func (*PowerSource) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{3}
}

func (x *PowerSource) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PowerSource) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

func (x *PowerSource) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

type PlayerRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PowerSources  []*PowerSource         `protobuf:"bytes,1,rep,name=power_sources,json=powerSources" json:"power_sources,omitempty"`
	Camera        *Point                 `protobuf:"bytes,2,opt,name=camera" json:"camera,omitempty"`
	UpgradeIds    []uint32               `protobuf:"varint,3,rep,name=upgrade_ids,json=upgradeIds" json:"upgrade_ids,omitempty"` // TODO: Add to UI observation?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRaw) Reset() {
	*x = PlayerRaw{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRaw) ProtoMessage() {}

func (x *PlayerRaw) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRaw.ProtoReflect.Descriptor instead.
func (*PlayerRaw) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerRaw) GetPowerSources() []*PowerSource {
	if x != nil {
		return x.PowerSources
	}
	return nil
}

func (x *PlayerRaw) GetCamera() *Point {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *PlayerRaw) GetUpgradeIds() []uint32 {
	if x != nil {
		return x.UpgradeIds
	}
	return nil
}

type UnitOrder struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AbilityId *uint32                `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*UnitOrder_TargetWorldSpacePos
	//	*UnitOrder_TargetUnitTag
	Target        isUnitOrder_Target `protobuf_oneof:"target"`
	Progress      *float32           `protobuf:"fixed32,4,opt,name=progress" json:"progress,omitempty"` // Progress of train abilities. Range: [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitOrder) Reset() {
	*x = UnitOrder{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitOrder) ProtoMessage() {}

func (x *UnitOrder) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitOrder.ProtoReflect.Descriptor instead.
func (*UnitOrder) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{5}
}

func (x *UnitOrder) GetAbilityId() uint32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

func (x *UnitOrder) GetTarget() isUnitOrder_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *UnitOrder) GetTargetWorldSpacePos() *Point {
	if x != nil {
		if x, ok := x.Target.(*UnitOrder_TargetWorldSpacePos); ok {
			return x.TargetWorldSpacePos
		}
	}
	return nil
}

func (x *UnitOrder) GetTargetUnitTag() uint64 {
	if x != nil {
		if x, ok := x.Target.(*UnitOrder_TargetUnitTag); ok {
			return x.TargetUnitTag
		}
	}
	return 0
}

func (x *UnitOrder) GetProgress() float32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

type isUnitOrder_Target interface {
	isUnitOrder_Target()
}

type UnitOrder_TargetWorldSpacePos struct {
	TargetWorldSpacePos *Point `protobuf:"bytes,2,opt,name=target_world_space_pos,json=targetWorldSpacePos,oneof"`
}

type UnitOrder_TargetUnitTag struct {
	TargetUnitTag uint64 `protobuf:"varint,3,opt,name=target_unit_tag,json=targetUnitTag,oneof"`
}

func (*UnitOrder_TargetWorldSpacePos) isUnitOrder_Target() {}

func (*UnitOrder_TargetUnitTag) isUnitOrder_Target() {}

type PassengerUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *uint64                `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	Health        *float32               `protobuf:"fixed32,2,opt,name=health" json:"health,omitempty"`
	HealthMax     *float32               `protobuf:"fixed32,3,opt,name=health_max,json=healthMax" json:"health_max,omitempty"`
	Shield        *float32               `protobuf:"fixed32,4,opt,name=shield" json:"shield,omitempty"`
	ShieldMax     *float32               `protobuf:"fixed32,7,opt,name=shield_max,json=shieldMax" json:"shield_max,omitempty"`
	Energy        *float32               `protobuf:"fixed32,5,opt,name=energy" json:"energy,omitempty"`
	EnergyMax     *float32               `protobuf:"fixed32,8,opt,name=energy_max,json=energyMax" json:"energy_max,omitempty"`
	UnitType      *uint32                `protobuf:"varint,6,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerUnit) Reset() {
	*x = PassengerUnit{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerUnit) ProtoMessage() {}

func (x *PassengerUnit) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerUnit.ProtoReflect.Descriptor instead.
func (*PassengerUnit) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{6}
}

func (x *PassengerUnit) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

func (x *PassengerUnit) GetHealth() float32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *PassengerUnit) GetHealthMax() float32 {
	if x != nil && x.HealthMax != nil {
		return *x.HealthMax
	}
	return 0
}

func (x *PassengerUnit) GetShield() float32 {
	if x != nil && x.Shield != nil {
		return *x.Shield
	}
	return 0
}

func (x *PassengerUnit) GetShieldMax() float32 {
	if x != nil && x.ShieldMax != nil {
		return *x.ShieldMax
	}
	return 0
}

func (x *PassengerUnit) GetEnergy() float32 {
	if x != nil && x.Energy != nil {
		return *x.Energy
	}
	return 0
}

func (x *PassengerUnit) GetEnergyMax() float32 {
	if x != nil && x.EnergyMax != nil {
		return *x.EnergyMax
	}
	return 0
}

func (x *PassengerUnit) GetUnitType() uint32 {
	if x != nil && x.UnitType != nil {
		return *x.UnitType
	}
	return 0
}

type RallyTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point" json:"point,omitempty"` // Will always be filled.
	Tag           *uint64                `protobuf:"varint,2,opt,name=tag" json:"tag,omitempty"`    // Only if it's targeting a unit.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyTarget) Reset() {
	*x = RallyTarget{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyTarget) ProtoMessage() {}

func (x *RallyTarget) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyTarget.ProtoReflect.Descriptor instead.
func (*RallyTarget) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{7}
}

func (x *RallyTarget) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *RallyTarget) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

type Unit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields are populated based on type/alliance
	DisplayType        *DisplayType `protobuf:"varint,1,opt,name=display_type,json=displayType,enum=SC2APIProtocol.DisplayType" json:"display_type,omitempty"`
	Alliance           *Alliance    `protobuf:"varint,2,opt,name=alliance,enum=SC2APIProtocol.Alliance" json:"alliance,omitempty"`
	Tag                *uint64      `protobuf:"varint,3,opt,name=tag" json:"tag,omitempty"` // Unique identifier for a unit
	UnitType           *uint32      `protobuf:"varint,4,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	Owner              *int32       `protobuf:"varint,5,opt,name=owner" json:"owner,omitempty"`
	Pos                *Point       `protobuf:"bytes,6,opt,name=pos" json:"pos,omitempty"`
	Facing             *float32     `protobuf:"fixed32,7,opt,name=facing" json:"facing,omitempty"`
	Radius             *float32     `protobuf:"fixed32,8,opt,name=radius" json:"radius,omitempty"`
	BuildProgress      *float32     `protobuf:"fixed32,9,opt,name=build_progress,json=buildProgress" json:"build_progress,omitempty"` // Range: [0.0, 1.0]
	Cloak              *CloakState  `protobuf:"varint,10,opt,name=cloak,enum=SC2APIProtocol.CloakState" json:"cloak,omitempty"`
	BuffIds            []uint32     `protobuf:"varint,27,rep,name=buff_ids,json=buffIds" json:"buff_ids,omitempty"`
	DetectRange        *float32     `protobuf:"fixed32,31,opt,name=detect_range,json=detectRange" json:"detect_range,omitempty"`
	RadarRange         *float32     `protobuf:"fixed32,32,opt,name=radar_range,json=radarRange" json:"radar_range,omitempty"`
	IsSelected         *bool        `protobuf:"varint,11,opt,name=is_selected,json=isSelected" json:"is_selected,omitempty"`
	IsOnScreen         *bool        `protobuf:"varint,12,opt,name=is_on_screen,json=isOnScreen" json:"is_on_screen,omitempty"` // Visible and within the camera frustrum.
	IsBlip             *bool        `protobuf:"varint,13,opt,name=is_blip,json=isBlip" json:"is_blip,omitempty"`               // Detected by sensor tower
	IsPowered          *bool        `protobuf:"varint,35,opt,name=is_powered,json=isPowered" json:"is_powered,omitempty"`
	IsActive           *bool        `protobuf:"varint,39,opt,name=is_active,json=isActive" json:"is_active,omitempty"` // Building is training/researching (ie animated).
	AttackUpgradeLevel *int32       `protobuf:"varint,40,opt,name=attack_upgrade_level,json=attackUpgradeLevel" json:"attack_upgrade_level,omitempty"`
	ArmorUpgradeLevel  *int32       `protobuf:"varint,41,opt,name=armor_upgrade_level,json=armorUpgradeLevel" json:"armor_upgrade_level,omitempty"`
	ShieldUpgradeLevel *int32       `protobuf:"varint,42,opt,name=shield_upgrade_level,json=shieldUpgradeLevel" json:"shield_upgrade_level,omitempty"`
	// Not populated for snapshots
	Health          *float32 `protobuf:"fixed32,14,opt,name=health" json:"health,omitempty"`
	HealthMax       *float32 `protobuf:"fixed32,15,opt,name=health_max,json=healthMax" json:"health_max,omitempty"`
	Shield          *float32 `protobuf:"fixed32,16,opt,name=shield" json:"shield,omitempty"`
	ShieldMax       *float32 `protobuf:"fixed32,36,opt,name=shield_max,json=shieldMax" json:"shield_max,omitempty"`
	Energy          *float32 `protobuf:"fixed32,17,opt,name=energy" json:"energy,omitempty"`
	EnergyMax       *float32 `protobuf:"fixed32,37,opt,name=energy_max,json=energyMax" json:"energy_max,omitempty"`
	MineralContents *int32   `protobuf:"varint,18,opt,name=mineral_contents,json=mineralContents" json:"mineral_contents,omitempty"`
	VespeneContents *int32   `protobuf:"varint,19,opt,name=vespene_contents,json=vespeneContents" json:"vespene_contents,omitempty"`
	IsFlying        *bool    `protobuf:"varint,20,opt,name=is_flying,json=isFlying" json:"is_flying,omitempty"`
	IsBurrowed      *bool    `protobuf:"varint,21,opt,name=is_burrowed,json=isBurrowed" json:"is_burrowed,omitempty"`
	IsHallucination *bool    `protobuf:"varint,38,opt,name=is_hallucination,json=isHallucination" json:"is_hallucination,omitempty"` // Unit is your own or detected as a hallucination.
	// Not populated for enemies
	Orders             []*UnitOrder     `protobuf:"bytes,22,rep,name=orders" json:"orders,omitempty"`
	AddOnTag           *uint64          `protobuf:"varint,23,opt,name=add_on_tag,json=addOnTag" json:"add_on_tag,omitempty"`
	Passengers         []*PassengerUnit `protobuf:"bytes,24,rep,name=passengers" json:"passengers,omitempty"`
	CargoSpaceTaken    *int32           `protobuf:"varint,25,opt,name=cargo_space_taken,json=cargoSpaceTaken" json:"cargo_space_taken,omitempty"`
	CargoSpaceMax      *int32           `protobuf:"varint,26,opt,name=cargo_space_max,json=cargoSpaceMax" json:"cargo_space_max,omitempty"`
	AssignedHarvesters *int32           `protobuf:"varint,28,opt,name=assigned_harvesters,json=assignedHarvesters" json:"assigned_harvesters,omitempty"`
	IdealHarvesters    *int32           `protobuf:"varint,29,opt,name=ideal_harvesters,json=idealHarvesters" json:"ideal_harvesters,omitempty"`
	WeaponCooldown     *float32         `protobuf:"fixed32,30,opt,name=weapon_cooldown,json=weaponCooldown" json:"weapon_cooldown,omitempty"`
	EngagedTargetTag   *uint64          `protobuf:"varint,34,opt,name=engaged_target_tag,json=engagedTargetTag" json:"engaged_target_tag,omitempty"`
	BuffDurationRemain *int32           `protobuf:"varint,43,opt,name=buff_duration_remain,json=buffDurationRemain" json:"buff_duration_remain,omitempty"` // How long a buff or unit is still around (eg mule, broodling, chronoboost).
	BuffDurationMax    *int32           `protobuf:"varint,44,opt,name=buff_duration_max,json=buffDurationMax" json:"buff_duration_max,omitempty"`          // How long the buff or unit is still around (eg mule, broodling, chronoboost).
	RallyTargets       []*RallyTarget   `protobuf:"bytes,45,rep,name=rally_targets,json=rallyTargets" json:"rally_targets,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Unit) Reset() {
	*x = Unit{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{8}
}

func (x *Unit) GetDisplayType() DisplayType {
	if x != nil && x.DisplayType != nil {
		return *x.DisplayType
	}
	return DisplayType_Visible
}

func (x *Unit) GetAlliance() Alliance {
	if x != nil && x.Alliance != nil {
		return *x.Alliance
	}
	return Alliance_Self
}

func (x *Unit) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

func (x *Unit) GetUnitType() uint32 {
	if x != nil && x.UnitType != nil {
		return *x.UnitType
	}
	return 0
}

func (x *Unit) GetOwner() int32 {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return 0
}

func (x *Unit) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Unit) GetFacing() float32 {
	if x != nil && x.Facing != nil {
		return *x.Facing
	}
	return 0
}

func (x *Unit) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

func (x *Unit) GetBuildProgress() float32 {
	if x != nil && x.BuildProgress != nil {
		return *x.BuildProgress
	}
	return 0
}

func (x *Unit) GetCloak() CloakState {
	if x != nil && x.Cloak != nil {
		return *x.Cloak
	}
	return CloakState_CloakedUnknown
}

func (x *Unit) GetBuffIds() []uint32 {
	if x != nil {
		return x.BuffIds
	}
	return nil
}

func (x *Unit) GetDetectRange() float32 {
	if x != nil && x.DetectRange != nil {
		return *x.DetectRange
	}
	return 0
}

func (x *Unit) GetRadarRange() float32 {
	if x != nil && x.RadarRange != nil {
		return *x.RadarRange
	}
	return 0
}

func (x *Unit) GetIsSelected() bool {
	if x != nil && x.IsSelected != nil {
		return *x.IsSelected
	}
	return false
}

func (x *Unit) GetIsOnScreen() bool {
	if x != nil && x.IsOnScreen != nil {
		return *x.IsOnScreen
	}
	return false
}

func (x *Unit) GetIsBlip() bool {
	if x != nil && x.IsBlip != nil {
		return *x.IsBlip
	}
	return false
}

func (x *Unit) GetIsPowered() bool {
	if x != nil && x.IsPowered != nil {
		return *x.IsPowered
	}
	return false
}

func (x *Unit) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *Unit) GetAttackUpgradeLevel() int32 {
	if x != nil && x.AttackUpgradeLevel != nil {
		return *x.AttackUpgradeLevel
	}
	return 0
}

func (x *Unit) GetArmorUpgradeLevel() int32 {
	if x != nil && x.ArmorUpgradeLevel != nil {
		return *x.ArmorUpgradeLevel
	}
	return 0
}

func (x *Unit) GetShieldUpgradeLevel() int32 {
	if x != nil && x.ShieldUpgradeLevel != nil {
		return *x.ShieldUpgradeLevel
	}
	return 0
}

func (x *Unit) GetHealth() float32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *Unit) GetHealthMax() float32 {
	if x != nil && x.HealthMax != nil {
		return *x.HealthMax
	}
	return 0
}

func (x *Unit) GetShield() float32 {
	if x != nil && x.Shield != nil {
		return *x.Shield
	}
	return 0
}

func (x *Unit) GetShieldMax() float32 {
	if x != nil && x.ShieldMax != nil {
		return *x.ShieldMax
	}
	return 0
}

func (x *Unit) GetEnergy() float32 {
	if x != nil && x.Energy != nil {
		return *x.Energy
	}
	return 0
}

func (x *Unit) GetEnergyMax() float32 {
	if x != nil && x.EnergyMax != nil {
		return *x.EnergyMax
	}
	return 0
}

func (x *Unit) GetMineralContents() int32 {
	if x != nil && x.MineralContents != nil {
		return *x.MineralContents
	}
	return 0
}

func (x *Unit) GetVespeneContents() int32 {
	if x != nil && x.VespeneContents != nil {
		return *x.VespeneContents
	}
	return 0
}

func (x *Unit) GetIsFlying() bool {
	if x != nil && x.IsFlying != nil {
		return *x.IsFlying
	}
	return false
}

func (x *Unit) GetIsBurrowed() bool {
	if x != nil && x.IsBurrowed != nil {
		return *x.IsBurrowed
	}
	return false
}

func (x *Unit) GetIsHallucination() bool {
	if x != nil && x.IsHallucination != nil {
		return *x.IsHallucination
	}
	return false
}

func (x *Unit) GetOrders() []*UnitOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Unit) GetAddOnTag() uint64 {
	if x != nil && x.AddOnTag != nil {
		return *x.AddOnTag
	}
	return 0
}

func (x *Unit) GetPassengers() []*PassengerUnit {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *Unit) GetCargoSpaceTaken() int32 {
	if x != nil && x.CargoSpaceTaken != nil {
		return *x.CargoSpaceTaken
	}
	return 0
}

func (x *Unit) GetCargoSpaceMax() int32 {
	if x != nil && x.CargoSpaceMax != nil {
		return *x.CargoSpaceMax
	}
	return 0
}

func (x *Unit) GetAssignedHarvesters() int32 {
	if x != nil && x.AssignedHarvesters != nil {
		return *x.AssignedHarvesters
	}
	return 0
}

func (x *Unit) GetIdealHarvesters() int32 {
	if x != nil && x.IdealHarvesters != nil {
		return *x.IdealHarvesters
	}
	return 0
}

func (x *Unit) GetWeaponCooldown() float32 {
	if x != nil && x.WeaponCooldown != nil {
		return *x.WeaponCooldown
	}
	return 0
}

func (x *Unit) GetEngagedTargetTag() uint64 {
	if x != nil && x.EngagedTargetTag != nil {
		return *x.EngagedTargetTag
	}
	return 0
}

func (x *Unit) GetBuffDurationRemain() int32 {
	if x != nil && x.BuffDurationRemain != nil {
		return *x.BuffDurationRemain
	}
	return 0
}

func (x *Unit) GetBuffDurationMax() int32 {
	if x != nil && x.BuffDurationMax != nil {
		return *x.BuffDurationMax
	}
	return 0
}

func (x *Unit) GetRallyTargets() []*RallyTarget {
	if x != nil {
		return x.RallyTargets
	}
	return nil
}

type MapState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visibility    *ImageData             `protobuf:"bytes,1,opt,name=visibility" json:"visibility,omitempty"` // 1 byte visibility layer.
	Creep         *ImageData             `protobuf:"bytes,2,opt,name=creep" json:"creep,omitempty"`           // 1 bit creep layer.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapState) Reset() {
	*x = MapState{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapState) ProtoMessage() {}

func (x *MapState) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapState.ProtoReflect.Descriptor instead.
func (*MapState) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{9}
}

func (x *MapState) GetVisibility() *ImageData {
	if x != nil {
		return x.Visibility
	}
	return nil
}

func (x *MapState) GetCreep() *ImageData {
	if x != nil {
		return x.Creep
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadUnits     []uint64               `protobuf:"varint,1,rep,name=dead_units,json=deadUnits" json:"dead_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetDeadUnits() []uint64 {
	if x != nil {
		return x.DeadUnits
	}
	return nil
}

type Effect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      *uint32                `protobuf:"varint,1,opt,name=effect_id,json=effectId" json:"effect_id,omitempty"`
	Pos           []*Point2D             `protobuf:"bytes,2,rep,name=pos" json:"pos,omitempty"` // Effect may impact multiple locations. (eg. Lurker attack)
	Alliance      *Alliance              `protobuf:"varint,3,opt,name=alliance,enum=SC2APIProtocol.Alliance" json:"alliance,omitempty"`
	Owner         *int32                 `protobuf:"varint,4,opt,name=owner" json:"owner,omitempty"`
	Radius        *float32               `protobuf:"fixed32,5,opt,name=radius" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{11}
}

func (x *Effect) GetEffectId() uint32 {
	if x != nil && x.EffectId != nil {
		return *x.EffectId
	}
	return 0
}

func (x *Effect) GetPos() []*Point2D {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Effect) GetAlliance() Alliance {
	if x != nil && x.Alliance != nil {
		return *x.Alliance
	}
	return Alliance_Self
}

func (x *Effect) GetOwner() int32 {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return 0
}

func (x *Effect) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

type ActionRaw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ActionRaw_UnitCommand
	//	*ActionRaw_CameraMove
	//	*ActionRaw_ToggleAutocast
	Action        isActionRaw_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRaw) Reset() {
	*x = ActionRaw{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRaw) ProtoMessage() {}

func (x *ActionRaw) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRaw.ProtoReflect.Descriptor instead.
func (*ActionRaw) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{12}
}

func (x *ActionRaw) GetAction() isActionRaw_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionRaw) GetUnitCommand() *ActionRawUnitCommand {
	if x != nil {
		if x, ok := x.Action.(*ActionRaw_UnitCommand); ok {
			return x.UnitCommand
		}
	}
	return nil
}

func (x *ActionRaw) GetCameraMove() *ActionRawCameraMove {
	if x != nil {
		if x, ok := x.Action.(*ActionRaw_CameraMove); ok {
			return x.CameraMove
		}
	}
	return nil
}

func (x *ActionRaw) GetToggleAutocast() *ActionRawToggleAutocast {
	if x != nil {
		if x, ok := x.Action.(*ActionRaw_ToggleAutocast); ok {
			return x.ToggleAutocast
		}
	}
	return nil
}

type isActionRaw_Action interface {
	isActionRaw_Action()
}

type ActionRaw_UnitCommand struct {
	UnitCommand *ActionRawUnitCommand `protobuf:"bytes,1,opt,name=unit_command,json=unitCommand,oneof"`
}

type ActionRaw_CameraMove struct {
	CameraMove *ActionRawCameraMove `protobuf:"bytes,2,opt,name=camera_move,json=cameraMove,oneof"`
}

type ActionRaw_ToggleAutocast struct {
	ToggleAutocast *ActionRawToggleAutocast `protobuf:"bytes,3,opt,name=toggle_autocast,json=toggleAutocast,oneof"`
}

func (*ActionRaw_UnitCommand) isActionRaw_Action() {}

func (*ActionRaw_CameraMove) isActionRaw_Action() {}

func (*ActionRaw_ToggleAutocast) isActionRaw_Action() {}

type ActionRawUnitCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AbilityId *int32                 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*ActionRawUnitCommand_TargetWorldSpacePos
	//	*ActionRawUnitCommand_TargetUnitTag
	Target        isActionRawUnitCommand_Target `protobuf_oneof:"target"`
	UnitTags      []uint64                      `protobuf:"varint,4,rep,name=unit_tags,json=unitTags" json:"unit_tags,omitempty"`
	QueueCommand  *bool                         `protobuf:"varint,5,opt,name=queue_command,json=queueCommand" json:"queue_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRawUnitCommand) Reset() {
	*x = ActionRawUnitCommand{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRawUnitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRawUnitCommand) ProtoMessage() {}

func (x *ActionRawUnitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRawUnitCommand.ProtoReflect.Descriptor instead.
func (*ActionRawUnitCommand) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{13}
}

func (x *ActionRawUnitCommand) GetAbilityId() int32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

func (x *ActionRawUnitCommand) GetTarget() isActionRawUnitCommand_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ActionRawUnitCommand) GetTargetWorldSpacePos() *Point2D {
	if x != nil {
		if x, ok := x.Target.(*ActionRawUnitCommand_TargetWorldSpacePos); ok {
			return x.TargetWorldSpacePos
		}
	}
	return nil
}

func (x *ActionRawUnitCommand) GetTargetUnitTag() uint64 {
	if x != nil {
		if x, ok := x.Target.(*ActionRawUnitCommand_TargetUnitTag); ok {
			return x.TargetUnitTag
		}
	}
	return 0
}

func (x *ActionRawUnitCommand) GetUnitTags() []uint64 {
	if x != nil {
		return x.UnitTags
	}
	return nil
}

func (x *ActionRawUnitCommand) GetQueueCommand() bool {
	if x != nil && x.QueueCommand != nil {
		return *x.QueueCommand
	}
	return false
}

type isActionRawUnitCommand_Target interface {
	isActionRawUnitCommand_Target()
}

type ActionRawUnitCommand_TargetWorldSpacePos struct {
	TargetWorldSpacePos *Point2D `protobuf:"bytes,2,opt,name=target_world_space_pos,json=targetWorldSpacePos,oneof"`
}

type ActionRawUnitCommand_TargetUnitTag struct {
	TargetUnitTag uint64 `protobuf:"varint,3,opt,name=target_unit_tag,json=targetUnitTag,oneof"`
}

func (*ActionRawUnitCommand_TargetWorldSpacePos) isActionRawUnitCommand_Target() {}

func (*ActionRawUnitCommand_TargetUnitTag) isActionRawUnitCommand_Target() {}

type ActionRawCameraMove struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CenterWorldSpace *Point                 `protobuf:"bytes,1,opt,name=center_world_space,json=centerWorldSpace" json:"center_world_space,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActionRawCameraMove) Reset() {
	*x = ActionRawCameraMove{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRawCameraMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRawCameraMove) ProtoMessage() {}

func (x *ActionRawCameraMove) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRawCameraMove.ProtoReflect.Descriptor instead.
func (*ActionRawCameraMove) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{14}
}

func (x *ActionRawCameraMove) GetCenterWorldSpace() *Point {
	if x != nil {
		return x.CenterWorldSpace
	}
	return nil
}

type ActionRawToggleAutocast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     *int32                 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	UnitTags      []uint64               `protobuf:"varint,2,rep,name=unit_tags,json=unitTags" json:"unit_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRawToggleAutocast) Reset() {
	*x = ActionRawToggleAutocast{}
	mi := &file_s2clientprotocol_raw_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRawToggleAutocast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRawToggleAutocast) ProtoMessage() {}

func (x *ActionRawToggleAutocast) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_raw_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRawToggleAutocast.ProtoReflect.Descriptor instead.
func (*ActionRawToggleAutocast) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_raw_proto_rawDescGZIP(), []int{15}
}

func (x *ActionRawToggleAutocast) GetAbilityId() int32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

func (x *ActionRawToggleAutocast) GetUnitTags() []uint64 {
	if x != nil {
		return x.UnitTags
	}
	return nil
}

var File_s2clientprotocol_raw_proto protoreflect.FileDescriptor

const file_s2clientprotocol_raw_proto_rawDesc = "" +
	"\n" +
	"\x1as2clientprotocol/raw.proto\x12\x0eSC2APIProtocol\x1a\x1ds2clientprotocol/common.proto\"\x83\x03\n" +
	"\bStartRaw\x122\n" +
	"\bmap_size\x18\x01 \x01(\v2\x17.SC2APIProtocol.Size2DIR\amapSize\x12<\n" +
	"\fpathing_grid\x18\x02 \x01(\v2\x19.SC2APIProtocol.ImageDataR\vpathingGrid\x12@\n" +
	"\x0eterrain_height\x18\x03 \x01(\v2\x19.SC2APIProtocol.ImageDataR\rterrainHeight\x12@\n" +
	"\x0eplacement_grid\x18\x04 \x01(\v2\x19.SC2APIProtocol.ImageDataR\rplacementGrid\x12?\n" +
	"\rplayable_area\x18\x05 \x01(\v2\x1a.SC2APIProtocol.RectangleIR\fplayableArea\x12@\n" +
	"\x0fstart_locations\x18\x06 \x03(\v2\x17.SC2APIProtocol.Point2DR\x0estartLocations\"\xb6\x02\n" +
	"\x0eObservationRaw\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.SC2APIProtocol.PlayerRawR\x06player\x12*\n" +
	"\x05units\x18\x02 \x03(\v2\x14.SC2APIProtocol.UnitR\x05units\x125\n" +
	"\tmap_state\x18\x03 \x01(\v2\x18.SC2APIProtocol.MapStateR\bmapState\x12+\n" +
	"\x05event\x18\x04 \x01(\v2\x15.SC2APIProtocol.EventR\x05event\x120\n" +
	"\aeffects\x18\x05 \x03(\v2\x16.SC2APIProtocol.EffectR\aeffects\x12/\n" +
	"\x05radar\x18\x06 \x03(\v2\x19.SC2APIProtocol.RadarRingR\x05radar\"L\n" +
	"\tRadarRing\x12'\n" +
	"\x03pos\x18\x01 \x01(\v2\x15.SC2APIProtocol.PointR\x03pos\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x02R\x06radius\"`\n" +
	"\vPowerSource\x12'\n" +
	"\x03pos\x18\x01 \x01(\v2\x15.SC2APIProtocol.PointR\x03pos\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x02R\x06radius\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\x04R\x03tag\"\x9d\x01\n" +
	"\tPlayerRaw\x12@\n" +
	"\rpower_sources\x18\x01 \x03(\v2\x1b.SC2APIProtocol.PowerSourceR\fpowerSources\x12-\n" +
	"\x06camera\x18\x02 \x01(\v2\x15.SC2APIProtocol.PointR\x06camera\x12\x1f\n" +
	"\vupgrade_ids\x18\x03 \x03(\rR\n" +
	"upgradeIds\"\xc8\x01\n" +
	"\tUnitOrder\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\rR\tabilityId\x12L\n" +
	"\x16target_world_space_pos\x18\x02 \x01(\v2\x15.SC2APIProtocol.PointH\x00R\x13targetWorldSpacePos\x12(\n" +
	"\x0ftarget_unit_tag\x18\x03 \x01(\x04H\x00R\rtargetUnitTag\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x02R\bprogressB\b\n" +
	"\x06target\"\xe3\x01\n" +
	"\rPassengerUnit\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\x04R\x03tag\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x02R\x06health\x12\x1d\n" +
	"\n" +
	"health_max\x18\x03 \x01(\x02R\thealthMax\x12\x16\n" +
	"\x06shield\x18\x04 \x01(\x02R\x06shield\x12\x1d\n" +
	"\n" +
	"shield_max\x18\a \x01(\x02R\tshieldMax\x12\x16\n" +
	"\x06energy\x18\x05 \x01(\x02R\x06energy\x12\x1d\n" +
	"\n" +
	"energy_max\x18\b \x01(\x02R\tenergyMax\x12\x1b\n" +
	"\tunit_type\x18\x06 \x01(\rR\bunitType\"L\n" +
	"\vRallyTarget\x12+\n" +
	"\x05point\x18\x01 \x01(\v2\x15.SC2APIProtocol.PointR\x05point\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\x04R\x03tag\"\x99\r\n" +
	"\x04Unit\x12>\n" +
	"\fdisplay_type\x18\x01 \x01(\x0e2\x1b.SC2APIProtocol.DisplayTypeR\vdisplayType\x124\n" +
	"\balliance\x18\x02 \x01(\x0e2\x18.SC2APIProtocol.AllianceR\balliance\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\x04R\x03tag\x12\x1b\n" +
	"\tunit_type\x18\x04 \x01(\rR\bunitType\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\x05R\x05owner\x12'\n" +
	"\x03pos\x18\x06 \x01(\v2\x15.SC2APIProtocol.PointR\x03pos\x12\x16\n" +
	"\x06facing\x18\a \x01(\x02R\x06facing\x12\x16\n" +
	"\x06radius\x18\b \x01(\x02R\x06radius\x12%\n" +
	"\x0ebuild_progress\x18\t \x01(\x02R\rbuildProgress\x120\n" +
	"\x05cloak\x18\n" +
	" \x01(\x0e2\x1a.SC2APIProtocol.CloakStateR\x05cloak\x12\x19\n" +
	"\bbuff_ids\x18\x1b \x03(\rR\abuffIds\x12!\n" +
	"\fdetect_range\x18\x1f \x01(\x02R\vdetectRange\x12\x1f\n" +
	"\vradar_range\x18  \x01(\x02R\n" +
	"radarRange\x12\x1f\n" +
	"\vis_selected\x18\v \x01(\bR\n" +
	"isSelected\x12 \n" +
	"\fis_on_screen\x18\f \x01(\bR\n" +
	"isOnScreen\x12\x17\n" +
	"\ais_blip\x18\r \x01(\bR\x06isBlip\x12\x1d\n" +
	"\n" +
	"is_powered\x18# \x01(\bR\tisPowered\x12\x1b\n" +
	"\tis_active\x18' \x01(\bR\bisActive\x120\n" +
	"\x14attack_upgrade_level\x18( \x01(\x05R\x12attackUpgradeLevel\x12.\n" +
	"\x13armor_upgrade_level\x18) \x01(\x05R\x11armorUpgradeLevel\x120\n" +
	"\x14shield_upgrade_level\x18* \x01(\x05R\x12shieldUpgradeLevel\x12\x16\n" +
	"\x06health\x18\x0e \x01(\x02R\x06health\x12\x1d\n" +
	"\n" +
	"health_max\x18\x0f \x01(\x02R\thealthMax\x12\x16\n" +
	"\x06shield\x18\x10 \x01(\x02R\x06shield\x12\x1d\n" +
	"\n" +
	"shield_max\x18$ \x01(\x02R\tshieldMax\x12\x16\n" +
	"\x06energy\x18\x11 \x01(\x02R\x06energy\x12\x1d\n" +
	"\n" +
	"energy_max\x18% \x01(\x02R\tenergyMax\x12)\n" +
	"\x10mineral_contents\x18\x12 \x01(\x05R\x0fmineralContents\x12)\n" +
	"\x10vespene_contents\x18\x13 \x01(\x05R\x0fvespeneContents\x12\x1b\n" +
	"\tis_flying\x18\x14 \x01(\bR\bisFlying\x12\x1f\n" +
	"\vis_burrowed\x18\x15 \x01(\bR\n" +
	"isBurrowed\x12)\n" +
	"\x10is_hallucination\x18& \x01(\bR\x0fisHallucination\x121\n" +
	"\x06orders\x18\x16 \x03(\v2\x19.SC2APIProtocol.UnitOrderR\x06orders\x12\x1c\n" +
	"\n" +
	"add_on_tag\x18\x17 \x01(\x04R\baddOnTag\x12=\n" +
	"\n" +
	"passengers\x18\x18 \x03(\v2\x1d.SC2APIProtocol.PassengerUnitR\n" +
	"passengers\x12*\n" +
	"\x11cargo_space_taken\x18\x19 \x01(\x05R\x0fcargoSpaceTaken\x12&\n" +
	"\x0fcargo_space_max\x18\x1a \x01(\x05R\rcargoSpaceMax\x12/\n" +
	"\x13assigned_harvesters\x18\x1c \x01(\x05R\x12assignedHarvesters\x12)\n" +
	"\x10ideal_harvesters\x18\x1d \x01(\x05R\x0fidealHarvesters\x12'\n" +
	"\x0fweapon_cooldown\x18\x1e \x01(\x02R\x0eweaponCooldown\x12,\n" +
	"\x12engaged_target_tag\x18\" \x01(\x04R\x10engagedTargetTag\x120\n" +
	"\x14buff_duration_remain\x18+ \x01(\x05R\x12buffDurationRemain\x12*\n" +
	"\x11buff_duration_max\x18, \x01(\x05R\x0fbuffDurationMax\x12@\n" +
	"\rrally_targets\x18- \x03(\v2\x1b.SC2APIProtocol.RallyTargetR\frallyTargets\"v\n" +
	"\bMapState\x129\n" +
	"\n" +
	"visibility\x18\x01 \x01(\v2\x19.SC2APIProtocol.ImageDataR\n" +
	"visibility\x12/\n" +
	"\x05creep\x18\x02 \x01(\v2\x19.SC2APIProtocol.ImageDataR\x05creep\"&\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"dead_units\x18\x01 \x03(\x04R\tdeadUnits\"\xb4\x01\n" +
	"\x06Effect\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\rR\beffectId\x12)\n" +
	"\x03pos\x18\x02 \x03(\v2\x17.SC2APIProtocol.Point2DR\x03pos\x124\n" +
	"\balliance\x18\x03 \x01(\x0e2\x18.SC2APIProtocol.AllianceR\balliance\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\x05R\x05owner\x12\x16\n" +
	"\x06radius\x18\x05 \x01(\x02R\x06radius\"\xfc\x01\n" +
	"\tActionRaw\x12I\n" +
	"\funit_command\x18\x01 \x01(\v2$.SC2APIProtocol.ActionRawUnitCommandH\x00R\vunitCommand\x12F\n" +
	"\vcamera_move\x18\x02 \x01(\v2#.SC2APIProtocol.ActionRawCameraMoveH\x00R\n" +
	"cameraMove\x12R\n" +
	"\x0ftoggle_autocast\x18\x03 \x01(\v2'.SC2APIProtocol.ActionRawToggleAutocastH\x00R\x0etoggleAutocastB\b\n" +
	"\x06action\"\xfb\x01\n" +
	"\x14ActionRawUnitCommand\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x12N\n" +
	"\x16target_world_space_pos\x18\x02 \x01(\v2\x17.SC2APIProtocol.Point2DH\x00R\x13targetWorldSpacePos\x12(\n" +
	"\x0ftarget_unit_tag\x18\x03 \x01(\x04H\x00R\rtargetUnitTag\x12\x1b\n" +
	"\tunit_tags\x18\x04 \x03(\x04R\bunitTags\x12#\n" +
	"\rqueue_command\x18\x05 \x01(\bR\fqueueCommandB\b\n" +
	"\x06target\"Z\n" +
	"\x13ActionRawCameraMove\x12C\n" +
	"\x12center_world_space\x18\x01 \x01(\v2\x15.SC2APIProtocol.PointR\x10centerWorldSpace\"U\n" +
	"\x17ActionRawToggleAutocast\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x12\x1b\n" +
	"\tunit_tags\x18\x02 \x03(\x04R\bunitTags*E\n" +
	"\vDisplayType\x12\v\n" +
	"\aVisible\x10\x01\x12\f\n" +
	"\bSnapshot\x10\x02\x12\n" +
	"\n" +
	"\x06Hidden\x10\x03\x12\x0f\n" +
	"\vPlaceholder\x10\x04*6\n" +
	"\bAlliance\x12\b\n" +
	"\x04Self\x10\x01\x12\b\n" +
	"\x04Ally\x10\x02\x12\v\n" +
	"\aNeutral\x10\x03\x12\t\n" +
	"\x05Enemy\x10\x04*e\n" +
	"\n" +
	"CloakState\x12\x12\n" +
	"\x0eCloakedUnknown\x10\x00\x12\v\n" +
	"\aCloaked\x10\x01\x12\x13\n" +
	"\x0fCloakedDetected\x10\x02\x12\x0e\n" +
	"\n" +
	"NotCloaked\x10\x03\x12\x11\n" +
	"\rCloakedAllied\x10\x04"

var (
	file_s2clientprotocol_raw_proto_rawDescOnce sync.Once
	file_s2clientprotocol_raw_proto_rawDescData []byte
)

func file_s2clientprotocol_raw_proto_rawDescGZIP() []byte {
	file_s2clientprotocol_raw_proto_rawDescOnce.Do(func() {
		file_s2clientprotocol_raw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2clientprotocol_raw_proto_rawDesc), len(file_s2clientprotocol_raw_proto_rawDesc)))
	})
	return file_s2clientprotocol_raw_proto_rawDescData
}

var file_s2clientprotocol_raw_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_s2clientprotocol_raw_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_s2clientprotocol_raw_proto_goTypes = []any{
	(DisplayType)(0),                // 0: SC2APIProtocol.DisplayType
	(Alliance)(0),                   // 1: SC2APIProtocol.Alliance
	(CloakState)(0),                 // 2: SC2APIProtocol.CloakState
	(*StartRaw)(nil),                // 3: SC2APIProtocol.StartRaw
	(*ObservationRaw)(nil),          // 4: SC2APIProtocol.ObservationRaw
	(*RadarRing)(nil),               // 5: SC2APIProtocol.RadarRing
	(*PowerSource)(nil),             // 6: SC2APIProtocol.PowerSource
	(*PlayerRaw)(nil),               // 7: SC2APIProtocol.PlayerRaw
	(*UnitOrder)(nil),               // 8: SC2APIProtocol.UnitOrder
	(*PassengerUnit)(nil),           // 9: SC2APIProtocol.PassengerUnit
	(*RallyTarget)(nil),             // 10: SC2APIProtocol.RallyTarget
	(*Unit)(nil),                    // 11: SC2APIProtocol.Unit
	(*MapState)(nil),                // 12: SC2APIProtocol.MapState
	(*Event)(nil),                   // 13: SC2APIProtocol.Event
	(*Effect)(nil),                  // 14: SC2APIProtocol.Effect
	(*ActionRaw)(nil),               // 15: SC2APIProtocol.ActionRaw
	(*ActionRawUnitCommand)(nil),    // 16: SC2APIProtocol.ActionRawUnitCommand
	(*ActionRawCameraMove)(nil),     // 17: SC2APIProtocol.ActionRawCameraMove
	(*ActionRawToggleAutocast)(nil), // 18: SC2APIProtocol.ActionRawToggleAutocast
	(*Size2DI)(nil),                 // 19: SC2APIProtocol.Size2DI
	(*ImageData)(nil),               // 20: SC2APIProtocol.ImageData
	(*RectangleI)(nil),              // 21: SC2APIProtocol.RectangleI
	(*Point2D)(nil),                 // 22: SC2APIProtocol.Point2D
	(*Point)(nil),                   // 23: SC2APIProtocol.Point
}
var file_s2clientprotocol_raw_proto_depIdxs = []int32{
	19, // 0: SC2APIProtocol.StartRaw.map_size:type_name -> SC2APIProtocol.Size2DI
	20, // 1: SC2APIProtocol.StartRaw.pathing_grid:type_name -> SC2APIProtocol.ImageData
	20, // 2: SC2APIProtocol.StartRaw.terrain_height:type_name -> SC2APIProtocol.ImageData
	20, // 3: SC2APIProtocol.StartRaw.placement_grid:type_name -> SC2APIProtocol.ImageData
	21, // 4: SC2APIProtocol.StartRaw.playable_area:type_name -> SC2APIProtocol.RectangleI
	22, // 5: SC2APIProtocol.StartRaw.start_locations:type_name -> SC2APIProtocol.Point2D
	7,  // 6: SC2APIProtocol.ObservationRaw.player:type_name -> SC2APIProtocol.PlayerRaw
	11, // 7: SC2APIProtocol.ObservationRaw.units:type_name -> SC2APIProtocol.Unit
	12, // 8: SC2APIProtocol.ObservationRaw.map_state:type_name -> SC2APIProtocol.MapState
	13, // 9: SC2APIProtocol.ObservationRaw.event:type_name -> SC2APIProtocol.Event
	14, // 10: SC2APIProtocol.ObservationRaw.effects:type_name -> SC2APIProtocol.Effect
	5,  // 11: SC2APIProtocol.ObservationRaw.radar:type_name -> SC2APIProtocol.RadarRing
	23, // 12: SC2APIProtocol.RadarRing.pos:type_name -> SC2APIProtocol.Point
	23, // 13: SC2APIProtocol.PowerSource.pos:type_name -> SC2APIProtocol.Point
	6,  // 14: SC2APIProtocol.PlayerRaw.power_sources:type_name -> SC2APIProtocol.PowerSource
	23, // 15: SC2APIProtocol.PlayerRaw.camera:type_name -> SC2APIProtocol.Point
	23, // 16: SC2APIProtocol.UnitOrder.target_world_space_pos:type_name -> SC2APIProtocol.Point
	23, // 17: SC2APIProtocol.RallyTarget.point:type_name -> SC2APIProtocol.Point
	0,  // 18: SC2APIProtocol.Unit.display_type:type_name -> SC2APIProtocol.DisplayType
	1,  // 19: SC2APIProtocol.Unit.alliance:type_name -> SC2APIProtocol.Alliance
	23, // 20: SC2APIProtocol.Unit.pos:type_name -> SC2APIProtocol.Point
	2,  // 21: SC2APIProtocol.Unit.cloak:type_name -> SC2APIProtocol.CloakState
	8,  // 22: SC2APIProtocol.Unit.orders:type_name -> SC2APIProtocol.UnitOrder
	9,  // 23: SC2APIProtocol.Unit.passengers:type_name -> SC2APIProtocol.PassengerUnit
	10, // 24: SC2APIProtocol.Unit.rally_targets:type_name -> SC2APIProtocol.RallyTarget
	20, // 25: SC2APIProtocol.MapState.visibility:type_name -> SC2APIProtocol.ImageData
	20, // 26: SC2APIProtocol.MapState.creep:type_name -> SC2APIProtocol.ImageData
	22, // 27: SC2APIProtocol.Effect.pos:type_name -> SC2APIProtocol.Point2D
	1,  // 28: SC2APIProtocol.Effect.alliance:type_name -> SC2APIProtocol.Alliance
	16, // 29: SC2APIProtocol.ActionRaw.unit_command:type_name -> SC2APIProtocol.ActionRawUnitCommand
	17, // 30: SC2APIProtocol.ActionRaw.camera_move:type_name -> SC2APIProtocol.ActionRawCameraMove
	18, // 31: SC2APIProtocol.ActionRaw.toggle_autocast:type_name -> SC2APIProtocol.ActionRawToggleAutocast
	22, // 32: SC2APIProtocol.ActionRawUnitCommand.target_world_space_pos:type_name -> SC2APIProtocol.Point2D
	23, // 33: SC2APIProtocol.ActionRawCameraMove.center_world_space:type_name -> SC2APIProtocol.Point
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_s2clientprotocol_raw_proto_init() }
func file_s2clientprotocol_raw_proto_init() {
	if File_s2clientprotocol_raw_proto != nil {
		return
	}
	file_s2clientprotocol_common_proto_init()
	file_s2clientprotocol_raw_proto_msgTypes[5].OneofWrappers = []any{
		(*UnitOrder_TargetWorldSpacePos)(nil),
		(*UnitOrder_TargetUnitTag)(nil),
	}
	file_s2clientprotocol_raw_proto_msgTypes[12].OneofWrappers = []any{
		(*ActionRaw_UnitCommand)(nil),
		(*ActionRaw_CameraMove)(nil),
		(*ActionRaw_ToggleAutocast)(nil),
	}
	file_s2clientprotocol_raw_proto_msgTypes[13].OneofWrappers = []any{
		(*ActionRawUnitCommand_TargetWorldSpacePos)(nil),
		(*ActionRawUnitCommand_TargetUnitTag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2clientprotocol_raw_proto_rawDesc), len(file_s2clientprotocol_raw_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2clientprotocol_raw_proto_goTypes,
		DependencyIndexes: file_s2clientprotocol_raw_proto_depIdxs,
		EnumInfos:         file_s2clientprotocol_raw_proto_enumTypes,
		MessageInfos:      file_s2clientprotocol_raw_proto_msgTypes,
	}.Build()
	File_s2clientprotocol_raw_proto = out.File
	file_s2clientprotocol_raw_proto_goTypes = nil
	file_s2clientprotocol_raw_proto_depIdxs = nil
}
