// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: s2clientprotocol/ui.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionControlGroup_ControlGroupAction int32

const (
	ActionControlGroup_Recall         ActionControlGroup_ControlGroupAction = 1 // Equivalent to number hotkey. Replaces current selection with control group.
	ActionControlGroup_Set            ActionControlGroup_ControlGroupAction = 2 // Equivalent to Control + number hotkey. Sets control group to current selection.
	ActionControlGroup_Append         ActionControlGroup_ControlGroupAction = 3 // Equivalent to Shift + number hotkey. Adds current selection into control group.
	ActionControlGroup_SetAndSteal    ActionControlGroup_ControlGroupAction = 4 // Equivalent to Control + Alt + number hotkey. Sets control group to current selection. Units are removed from other control groups.
	ActionControlGroup_AppendAndSteal ActionControlGroup_ControlGroupAction = 5 // Equivalent to Shift + Alt + number hotkey. Adds current selection into control group. Units are removed from other control groups.
)

// Enum value maps for ActionControlGroup_ControlGroupAction.
var (
	ActionControlGroup_ControlGroupAction_name = map[int32]string{
		1: "Recall",
		2: "Set",
		3: "Append",
		4: "SetAndSteal",
		5: "AppendAndSteal",
	}
	ActionControlGroup_ControlGroupAction_value = map[string]int32{
		"Recall":         1,
		"Set":            2,
		"Append":         3,
		"SetAndSteal":    4,
		"AppendAndSteal": 5,
	}
)

func (x ActionControlGroup_ControlGroupAction) Enum() *ActionControlGroup_ControlGroupAction {
	p := new(ActionControlGroup_ControlGroupAction)
	*p = x
	return p
}

func (x ActionControlGroup_ControlGroupAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionControlGroup_ControlGroupAction) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_ui_proto_enumTypes[0].Descriptor()
}

func (ActionControlGroup_ControlGroupAction) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_ui_proto_enumTypes[0]
}

func (x ActionControlGroup_ControlGroupAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActionControlGroup_ControlGroupAction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActionControlGroup_ControlGroupAction(num)
	return nil
}

// Deprecated: Use ActionControlGroup_ControlGroupAction.Descriptor instead.
func (ActionControlGroup_ControlGroupAction) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{9, 0}
}

type ActionSelectIdleWorker_Type int32

const (
	ActionSelectIdleWorker_Set    ActionSelectIdleWorker_Type = 1 // Equivalent to click with no modifiers. Replaces selection with single idle worker.
	ActionSelectIdleWorker_Add    ActionSelectIdleWorker_Type = 2 // Equivalent to shift+click. Adds single idle worker to current selection.
	ActionSelectIdleWorker_All    ActionSelectIdleWorker_Type = 3 // Equivalent to control+click. Selects all idle workers.
	ActionSelectIdleWorker_AddAll ActionSelectIdleWorker_Type = 4 // Equivalent to shift+control+click. Adds all idle workers to current selection.
)

// Enum value maps for ActionSelectIdleWorker_Type.
var (
	ActionSelectIdleWorker_Type_name = map[int32]string{
		1: "Set",
		2: "Add",
		3: "All",
		4: "AddAll",
	}
	ActionSelectIdleWorker_Type_value = map[string]int32{
		"Set":    1,
		"Add":    2,
		"All":    3,
		"AddAll": 4,
	}
)

func (x ActionSelectIdleWorker_Type) Enum() *ActionSelectIdleWorker_Type {
	p := new(ActionSelectIdleWorker_Type)
	*p = x
	return p
}

func (x ActionSelectIdleWorker_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionSelectIdleWorker_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_ui_proto_enumTypes[1].Descriptor()
}

func (ActionSelectIdleWorker_Type) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_ui_proto_enumTypes[1]
}

func (x ActionSelectIdleWorker_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActionSelectIdleWorker_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActionSelectIdleWorker_Type(num)
	return nil
}

// Deprecated: Use ActionSelectIdleWorker_Type.Descriptor instead.
func (ActionSelectIdleWorker_Type) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{13, 0}
}

type ActionMultiPanel_Type int32

const (
	ActionMultiPanel_SingleSelect      ActionMultiPanel_Type = 1 // Click on icon
	ActionMultiPanel_DeselectUnit      ActionMultiPanel_Type = 2 // Shift Click on icon
	ActionMultiPanel_SelectAllOfType   ActionMultiPanel_Type = 3 // Control Click on icon.
	ActionMultiPanel_DeselectAllOfType ActionMultiPanel_Type = 4 // Control+Shift Click on icon.
)

// Enum value maps for ActionMultiPanel_Type.
var (
	ActionMultiPanel_Type_name = map[int32]string{
		1: "SingleSelect",
		2: "DeselectUnit",
		3: "SelectAllOfType",
		4: "DeselectAllOfType",
	}
	ActionMultiPanel_Type_value = map[string]int32{
		"SingleSelect":      1,
		"DeselectUnit":      2,
		"SelectAllOfType":   3,
		"DeselectAllOfType": 4,
	}
)

func (x ActionMultiPanel_Type) Enum() *ActionMultiPanel_Type {
	p := new(ActionMultiPanel_Type)
	*p = x
	return p
}

func (x ActionMultiPanel_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionMultiPanel_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_s2clientprotocol_ui_proto_enumTypes[2].Descriptor()
}

func (ActionMultiPanel_Type) Type() protoreflect.EnumType {
	return &file_s2clientprotocol_ui_proto_enumTypes[2]
}

func (x ActionMultiPanel_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActionMultiPanel_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActionMultiPanel_Type(num)
	return nil
}

// Deprecated: Use ActionMultiPanel_Type.Descriptor instead.
func (ActionMultiPanel_Type) EnumDescriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{14, 0}
}

type ObservationUI struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Groups []*ControlGroup        `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	// Types that are valid to be assigned to Panel:
	//
	//	*ObservationUI_Single
	//	*ObservationUI_Multi
	//	*ObservationUI_Cargo
	//	*ObservationUI_Production
	Panel         isObservationUI_Panel `protobuf_oneof:"panel"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationUI) Reset() {
	*x = ObservationUI{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationUI) ProtoMessage() {}

func (x *ObservationUI) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationUI.ProtoReflect.Descriptor instead.
func (*ObservationUI) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{0}
}

func (x *ObservationUI) GetGroups() []*ControlGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ObservationUI) GetPanel() isObservationUI_Panel {
	if x != nil {
		return x.Panel
	}
	return nil
}

func (x *ObservationUI) GetSingle() *SinglePanel {
	if x != nil {
		if x, ok := x.Panel.(*ObservationUI_Single); ok {
			return x.Single
		}
	}
	return nil
}

func (x *ObservationUI) GetMulti() *MultiPanel {
	if x != nil {
		if x, ok := x.Panel.(*ObservationUI_Multi); ok {
			return x.Multi
		}
	}
	return nil
}

func (x *ObservationUI) GetCargo() *CargoPanel {
	if x != nil {
		if x, ok := x.Panel.(*ObservationUI_Cargo); ok {
			return x.Cargo
		}
	}
	return nil
}

func (x *ObservationUI) GetProduction() *ProductionPanel {
	if x != nil {
		if x, ok := x.Panel.(*ObservationUI_Production); ok {
			return x.Production
		}
	}
	return nil
}

type isObservationUI_Panel interface {
	isObservationUI_Panel()
}

type ObservationUI_Single struct {
	Single *SinglePanel `protobuf:"bytes,2,opt,name=single,oneof"`
}

type ObservationUI_Multi struct {
	Multi *MultiPanel `protobuf:"bytes,3,opt,name=multi,oneof"`
}

type ObservationUI_Cargo struct {
	Cargo *CargoPanel `protobuf:"bytes,4,opt,name=cargo,oneof"`
}

type ObservationUI_Production struct {
	Production *ProductionPanel `protobuf:"bytes,5,opt,name=production,oneof"`
}

func (*ObservationUI_Single) isObservationUI_Panel() {}

func (*ObservationUI_Multi) isObservationUI_Panel() {}

func (*ObservationUI_Cargo) isObservationUI_Panel() {}

func (*ObservationUI_Production) isObservationUI_Panel() {}

type ControlGroup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControlGroupIndex *uint32                `protobuf:"varint,1,opt,name=control_group_index,json=controlGroupIndex" json:"control_group_index,omitempty"`
	LeaderUnitType    *uint32                `protobuf:"varint,2,opt,name=leader_unit_type,json=leaderUnitType" json:"leader_unit_type,omitempty"`
	Count             *uint32                `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControlGroup) Reset() {
	*x = ControlGroup{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlGroup) ProtoMessage() {}

func (x *ControlGroup) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlGroup.ProtoReflect.Descriptor instead.
func (*ControlGroup) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{1}
}

func (x *ControlGroup) GetControlGroupIndex() uint32 {
	if x != nil && x.ControlGroupIndex != nil {
		return *x.ControlGroupIndex
	}
	return 0
}

func (x *ControlGroup) GetLeaderUnitType() uint32 {
	if x != nil && x.LeaderUnitType != nil {
		return *x.LeaderUnitType
	}
	return 0
}

func (x *ControlGroup) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type UnitInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UnitType            *uint32                `protobuf:"varint,1,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	PlayerRelative      *uint32                `protobuf:"varint,2,opt,name=player_relative,json=playerRelative" json:"player_relative,omitempty"`
	Health              *int32                 `protobuf:"varint,3,opt,name=health" json:"health,omitempty"`
	Shields             *int32                 `protobuf:"varint,4,opt,name=shields" json:"shields,omitempty"`
	Energy              *int32                 `protobuf:"varint,5,opt,name=energy" json:"energy,omitempty"`
	TransportSlotsTaken *int32                 `protobuf:"varint,6,opt,name=transport_slots_taken,json=transportSlotsTaken" json:"transport_slots_taken,omitempty"`
	BuildProgress       *float32               `protobuf:"fixed32,7,opt,name=build_progress,json=buildProgress" json:"build_progress,omitempty"` // Range: [0.0, 1.0]
	AddOn               *UnitInfo              `protobuf:"bytes,8,opt,name=add_on,json=addOn" json:"add_on,omitempty"`
	MaxHealth           *int32                 `protobuf:"varint,9,opt,name=max_health,json=maxHealth" json:"max_health,omitempty"`
	MaxShields          *int32                 `protobuf:"varint,10,opt,name=max_shields,json=maxShields" json:"max_shields,omitempty"`
	MaxEnergy           *int32                 `protobuf:"varint,11,opt,name=max_energy,json=maxEnergy" json:"max_energy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UnitInfo) Reset() {
	*x = UnitInfo{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitInfo) ProtoMessage() {}

func (x *UnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitInfo.ProtoReflect.Descriptor instead.
func (*UnitInfo) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{2}
}

func (x *UnitInfo) GetUnitType() uint32 {
	if x != nil && x.UnitType != nil {
		return *x.UnitType
	}
	return 0
}

func (x *UnitInfo) GetPlayerRelative() uint32 {
	if x != nil && x.PlayerRelative != nil {
		return *x.PlayerRelative
	}
	return 0
}

func (x *UnitInfo) GetHealth() int32 {
	if x != nil && x.Health != nil {
		return *x.Health
	}
	return 0
}

func (x *UnitInfo) GetShields() int32 {
	if x != nil && x.Shields != nil {
		return *x.Shields
	}
	return 0
}

func (x *UnitInfo) GetEnergy() int32 {
	if x != nil && x.Energy != nil {
		return *x.Energy
	}
	return 0
}

func (x *UnitInfo) GetTransportSlotsTaken() int32 {
	if x != nil && x.TransportSlotsTaken != nil {
		return *x.TransportSlotsTaken
	}
	return 0
}

func (x *UnitInfo) GetBuildProgress() float32 {
	if x != nil && x.BuildProgress != nil {
		return *x.BuildProgress
	}
	return 0
}

func (x *UnitInfo) GetAddOn() *UnitInfo {
	if x != nil {
		return x.AddOn
	}
	return nil
}

func (x *UnitInfo) GetMaxHealth() int32 {
	if x != nil && x.MaxHealth != nil {
		return *x.MaxHealth
	}
	return 0
}

func (x *UnitInfo) GetMaxShields() int32 {
	if x != nil && x.MaxShields != nil {
		return *x.MaxShields
	}
	return 0
}

func (x *UnitInfo) GetMaxEnergy() int32 {
	if x != nil && x.MaxEnergy != nil {
		return *x.MaxEnergy
	}
	return 0
}

type SinglePanel struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Unit               *UnitInfo              `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	AttackUpgradeLevel *int32                 `protobuf:"varint,2,opt,name=attack_upgrade_level,json=attackUpgradeLevel" json:"attack_upgrade_level,omitempty"`
	ArmorUpgradeLevel  *int32                 `protobuf:"varint,3,opt,name=armor_upgrade_level,json=armorUpgradeLevel" json:"armor_upgrade_level,omitempty"`
	ShieldUpgradeLevel *int32                 `protobuf:"varint,4,opt,name=shield_upgrade_level,json=shieldUpgradeLevel" json:"shield_upgrade_level,omitempty"`
	Buffs              []int32                `protobuf:"varint,5,rep,name=buffs" json:"buffs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SinglePanel) Reset() {
	*x = SinglePanel{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePanel) ProtoMessage() {}

func (x *SinglePanel) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePanel.ProtoReflect.Descriptor instead.
func (*SinglePanel) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{3}
}

func (x *SinglePanel) GetUnit() *UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *SinglePanel) GetAttackUpgradeLevel() int32 {
	if x != nil && x.AttackUpgradeLevel != nil {
		return *x.AttackUpgradeLevel
	}
	return 0
}

func (x *SinglePanel) GetArmorUpgradeLevel() int32 {
	if x != nil && x.ArmorUpgradeLevel != nil {
		return *x.ArmorUpgradeLevel
	}
	return 0
}

func (x *SinglePanel) GetShieldUpgradeLevel() int32 {
	if x != nil && x.ShieldUpgradeLevel != nil {
		return *x.ShieldUpgradeLevel
	}
	return 0
}

func (x *SinglePanel) GetBuffs() []int32 {
	if x != nil {
		return x.Buffs
	}
	return nil
}

type MultiPanel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitInfo            `protobuf:"bytes,1,rep,name=units" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPanel) Reset() {
	*x = MultiPanel{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPanel) ProtoMessage() {}

func (x *MultiPanel) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPanel.ProtoReflect.Descriptor instead.
func (*MultiPanel) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{4}
}

func (x *MultiPanel) GetUnits() []*UnitInfo {
	if x != nil {
		return x.Units
	}
	return nil
}

type CargoPanel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Unit           *UnitInfo              `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Passengers     []*UnitInfo            `protobuf:"bytes,2,rep,name=passengers" json:"passengers,omitempty"`
	SlotsAvailable *int32                 `protobuf:"varint,3,opt,name=slots_available,json=slotsAvailable" json:"slots_available,omitempty"` // TODO: Change to cargo size
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CargoPanel) Reset() {
	*x = CargoPanel{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoPanel) ProtoMessage() {}

func (x *CargoPanel) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoPanel.ProtoReflect.Descriptor instead.
func (*CargoPanel) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{5}
}

func (x *CargoPanel) GetUnit() *UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *CargoPanel) GetPassengers() []*UnitInfo {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *CargoPanel) GetSlotsAvailable() int32 {
	if x != nil && x.SlotsAvailable != nil {
		return *x.SlotsAvailable
	}
	return 0
}

type BuildItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     *uint32                `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	BuildProgress *float32               `protobuf:"fixed32,2,opt,name=build_progress,json=buildProgress" json:"build_progress,omitempty"` // Range: [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildItem) Reset() {
	*x = BuildItem{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildItem) ProtoMessage() {}

func (x *BuildItem) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildItem.ProtoReflect.Descriptor instead.
func (*BuildItem) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{6}
}

func (x *BuildItem) GetAbilityId() uint32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

func (x *BuildItem) GetBuildProgress() float32 {
	if x != nil && x.BuildProgress != nil {
		return *x.BuildProgress
	}
	return 0
}

type ProductionPanel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Unit  *UnitInfo              `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	// build_queue ONLY gives information about units that are being produced.
	// Use production_queue instead to see both units being trained as well as research in the queue.
	BuildQueue      []*UnitInfo  `protobuf:"bytes,2,rep,name=build_queue,json=buildQueue" json:"build_queue,omitempty"`
	ProductionQueue []*BuildItem `protobuf:"bytes,3,rep,name=production_queue,json=productionQueue" json:"production_queue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductionPanel) Reset() {
	*x = ProductionPanel{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionPanel) ProtoMessage() {}

func (x *ProductionPanel) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionPanel.ProtoReflect.Descriptor instead.
func (*ProductionPanel) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{7}
}

func (x *ProductionPanel) GetUnit() *UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *ProductionPanel) GetBuildQueue() []*UnitInfo {
	if x != nil {
		return x.BuildQueue
	}
	return nil
}

func (x *ProductionPanel) GetProductionQueue() []*BuildItem {
	if x != nil {
		return x.ProductionQueue
	}
	return nil
}

type ActionUI struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ActionUI_ControlGroup
	//	*ActionUI_SelectArmy
	//	*ActionUI_SelectWarpGates
	//	*ActionUI_SelectLarva
	//	*ActionUI_SelectIdleWorker
	//	*ActionUI_MultiPanel
	//	*ActionUI_CargoPanel
	//	*ActionUI_ProductionPanel
	//	*ActionUI_ToggleAutocast
	Action        isActionUI_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionUI) Reset() {
	*x = ActionUI{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionUI) ProtoMessage() {}

func (x *ActionUI) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionUI.ProtoReflect.Descriptor instead.
func (*ActionUI) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{8}
}

func (x *ActionUI) GetAction() isActionUI_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionUI) GetControlGroup() *ActionControlGroup {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_ControlGroup); ok {
			return x.ControlGroup
		}
	}
	return nil
}

func (x *ActionUI) GetSelectArmy() *ActionSelectArmy {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_SelectArmy); ok {
			return x.SelectArmy
		}
	}
	return nil
}

func (x *ActionUI) GetSelectWarpGates() *ActionSelectWarpGates {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_SelectWarpGates); ok {
			return x.SelectWarpGates
		}
	}
	return nil
}

func (x *ActionUI) GetSelectLarva() *ActionSelectLarva {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_SelectLarva); ok {
			return x.SelectLarva
		}
	}
	return nil
}

func (x *ActionUI) GetSelectIdleWorker() *ActionSelectIdleWorker {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_SelectIdleWorker); ok {
			return x.SelectIdleWorker
		}
	}
	return nil
}

func (x *ActionUI) GetMultiPanel() *ActionMultiPanel {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_MultiPanel); ok {
			return x.MultiPanel
		}
	}
	return nil
}

func (x *ActionUI) GetCargoPanel() *ActionCargoPanelUnload {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_CargoPanel); ok {
			return x.CargoPanel
		}
	}
	return nil
}

func (x *ActionUI) GetProductionPanel() *ActionProductionPanelRemoveFromQueue {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_ProductionPanel); ok {
			return x.ProductionPanel
		}
	}
	return nil
}

func (x *ActionUI) GetToggleAutocast() *ActionToggleAutocast {
	if x != nil {
		if x, ok := x.Action.(*ActionUI_ToggleAutocast); ok {
			return x.ToggleAutocast
		}
	}
	return nil
}

type isActionUI_Action interface {
	isActionUI_Action()
}

type ActionUI_ControlGroup struct {
	ControlGroup *ActionControlGroup `protobuf:"bytes,1,opt,name=control_group,json=controlGroup,oneof"`
}

type ActionUI_SelectArmy struct {
	SelectArmy *ActionSelectArmy `protobuf:"bytes,2,opt,name=select_army,json=selectArmy,oneof"`
}

type ActionUI_SelectWarpGates struct {
	SelectWarpGates *ActionSelectWarpGates `protobuf:"bytes,3,opt,name=select_warp_gates,json=selectWarpGates,oneof"`
}

type ActionUI_SelectLarva struct {
	SelectLarva *ActionSelectLarva `protobuf:"bytes,4,opt,name=select_larva,json=selectLarva,oneof"`
}

type ActionUI_SelectIdleWorker struct {
	SelectIdleWorker *ActionSelectIdleWorker `protobuf:"bytes,5,opt,name=select_idle_worker,json=selectIdleWorker,oneof"`
}

type ActionUI_MultiPanel struct {
	MultiPanel *ActionMultiPanel `protobuf:"bytes,6,opt,name=multi_panel,json=multiPanel,oneof"`
}

type ActionUI_CargoPanel struct {
	CargoPanel *ActionCargoPanelUnload `protobuf:"bytes,7,opt,name=cargo_panel,json=cargoPanel,oneof"`
}

type ActionUI_ProductionPanel struct {
	ProductionPanel *ActionProductionPanelRemoveFromQueue `protobuf:"bytes,8,opt,name=production_panel,json=productionPanel,oneof"`
}

type ActionUI_ToggleAutocast struct {
	ToggleAutocast *ActionToggleAutocast `protobuf:"bytes,9,opt,name=toggle_autocast,json=toggleAutocast,oneof"`
}

func (*ActionUI_ControlGroup) isActionUI_Action() {}

func (*ActionUI_SelectArmy) isActionUI_Action() {}

func (*ActionUI_SelectWarpGates) isActionUI_Action() {}

func (*ActionUI_SelectLarva) isActionUI_Action() {}

func (*ActionUI_SelectIdleWorker) isActionUI_Action() {}

func (*ActionUI_MultiPanel) isActionUI_Action() {}

func (*ActionUI_CargoPanel) isActionUI_Action() {}

func (*ActionUI_ProductionPanel) isActionUI_Action() {}

func (*ActionUI_ToggleAutocast) isActionUI_Action() {}

type ActionControlGroup struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	Action            *ActionControlGroup_ControlGroupAction `protobuf:"varint,1,opt,name=action,enum=SC2APIProtocol.ActionControlGroup_ControlGroupAction" json:"action,omitempty"`
	ControlGroupIndex *uint32                                `protobuf:"varint,2,opt,name=control_group_index,json=controlGroupIndex" json:"control_group_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActionControlGroup) Reset() {
	*x = ActionControlGroup{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionControlGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionControlGroup) ProtoMessage() {}

func (x *ActionControlGroup) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionControlGroup.ProtoReflect.Descriptor instead.
func (*ActionControlGroup) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{9}
}

func (x *ActionControlGroup) GetAction() ActionControlGroup_ControlGroupAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ActionControlGroup_Recall
}

func (x *ActionControlGroup) GetControlGroupIndex() uint32 {
	if x != nil && x.ControlGroupIndex != nil {
		return *x.ControlGroupIndex
	}
	return 0
}

type ActionSelectArmy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelectionAdd  *bool                  `protobuf:"varint,1,opt,name=selection_add,json=selectionAdd" json:"selection_add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSelectArmy) Reset() {
	*x = ActionSelectArmy{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSelectArmy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSelectArmy) ProtoMessage() {}

func (x *ActionSelectArmy) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSelectArmy.ProtoReflect.Descriptor instead.
func (*ActionSelectArmy) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{10}
}

func (x *ActionSelectArmy) GetSelectionAdd() bool {
	if x != nil && x.SelectionAdd != nil {
		return *x.SelectionAdd
	}
	return false
}

type ActionSelectWarpGates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelectionAdd  *bool                  `protobuf:"varint,1,opt,name=selection_add,json=selectionAdd" json:"selection_add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSelectWarpGates) Reset() {
	*x = ActionSelectWarpGates{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSelectWarpGates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSelectWarpGates) ProtoMessage() {}

func (x *ActionSelectWarpGates) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSelectWarpGates.ProtoReflect.Descriptor instead.
func (*ActionSelectWarpGates) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{11}
}

func (x *ActionSelectWarpGates) GetSelectionAdd() bool {
	if x != nil && x.SelectionAdd != nil {
		return *x.SelectionAdd
	}
	return false
}

type ActionSelectLarva struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSelectLarva) Reset() {
	*x = ActionSelectLarva{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSelectLarva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSelectLarva) ProtoMessage() {}

func (x *ActionSelectLarva) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSelectLarva.ProtoReflect.Descriptor instead.
func (*ActionSelectLarva) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{12}
}

type ActionSelectIdleWorker struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          *ActionSelectIdleWorker_Type `protobuf:"varint,1,opt,name=type,enum=SC2APIProtocol.ActionSelectIdleWorker_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSelectIdleWorker) Reset() {
	*x = ActionSelectIdleWorker{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSelectIdleWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSelectIdleWorker) ProtoMessage() {}

func (x *ActionSelectIdleWorker) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSelectIdleWorker.ProtoReflect.Descriptor instead.
func (*ActionSelectIdleWorker) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{13}
}

func (x *ActionSelectIdleWorker) GetType() ActionSelectIdleWorker_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ActionSelectIdleWorker_Set
}

type ActionMultiPanel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *ActionMultiPanel_Type `protobuf:"varint,1,opt,name=type,enum=SC2APIProtocol.ActionMultiPanel_Type" json:"type,omitempty"`
	UnitIndex     *int32                 `protobuf:"varint,2,opt,name=unit_index,json=unitIndex" json:"unit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMultiPanel) Reset() {
	*x = ActionMultiPanel{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMultiPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMultiPanel) ProtoMessage() {}

func (x *ActionMultiPanel) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMultiPanel.ProtoReflect.Descriptor instead.
func (*ActionMultiPanel) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{14}
}

func (x *ActionMultiPanel) GetType() ActionMultiPanel_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ActionMultiPanel_SingleSelect
}

func (x *ActionMultiPanel) GetUnitIndex() int32 {
	if x != nil && x.UnitIndex != nil {
		return *x.UnitIndex
	}
	return 0
}

type ActionCargoPanelUnload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     *int32                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex" json:"unit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCargoPanelUnload) Reset() {
	*x = ActionCargoPanelUnload{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCargoPanelUnload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCargoPanelUnload) ProtoMessage() {}

func (x *ActionCargoPanelUnload) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCargoPanelUnload.ProtoReflect.Descriptor instead.
func (*ActionCargoPanelUnload) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{15}
}

func (x *ActionCargoPanelUnload) GetUnitIndex() int32 {
	if x != nil && x.UnitIndex != nil {
		return *x.UnitIndex
	}
	return 0
}

type ActionProductionPanelRemoveFromQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitIndex     *int32                 `protobuf:"varint,1,opt,name=unit_index,json=unitIndex" json:"unit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionProductionPanelRemoveFromQueue) Reset() {
	*x = ActionProductionPanelRemoveFromQueue{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionProductionPanelRemoveFromQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProductionPanelRemoveFromQueue) ProtoMessage() {}

func (x *ActionProductionPanelRemoveFromQueue) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProductionPanelRemoveFromQueue.ProtoReflect.Descriptor instead.
func (*ActionProductionPanelRemoveFromQueue) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{16}
}

func (x *ActionProductionPanelRemoveFromQueue) GetUnitIndex() int32 {
	if x != nil && x.UnitIndex != nil {
		return *x.UnitIndex
	}
	return 0
}

type ActionToggleAutocast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbilityId     *int32                 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionToggleAutocast) Reset() {
	*x = ActionToggleAutocast{}
	mi := &file_s2clientprotocol_ui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionToggleAutocast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionToggleAutocast) ProtoMessage() {}

func (x *ActionToggleAutocast) ProtoReflect() protoreflect.Message {
	mi := &file_s2clientprotocol_ui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionToggleAutocast.ProtoReflect.Descriptor instead.
func (*ActionToggleAutocast) Descriptor() ([]byte, []int) {
	return file_s2clientprotocol_ui_proto_rawDescGZIP(), []int{17}
}

func (x *ActionToggleAutocast) GetAbilityId() int32 {
	if x != nil && x.AbilityId != nil {
		return *x.AbilityId
	}
	return 0
}

var File_s2clientprotocol_ui_proto protoreflect.FileDescriptor

const file_s2clientprotocol_ui_proto_rawDesc = "" +
	"\n" +
	"\x19s2clientprotocol/ui.proto\x12\x0eSC2APIProtocol\"\xb0\x02\n" +
	"\rObservationUI\x124\n" +
	"\x06groups\x18\x01 \x03(\v2\x1c.SC2APIProtocol.ControlGroupR\x06groups\x125\n" +
	"\x06single\x18\x02 \x01(\v2\x1b.SC2APIProtocol.SinglePanelH\x00R\x06single\x122\n" +
	"\x05multi\x18\x03 \x01(\v2\x1a.SC2APIProtocol.MultiPanelH\x00R\x05multi\x122\n" +
	"\x05cargo\x18\x04 \x01(\v2\x1a.SC2APIProtocol.CargoPanelH\x00R\x05cargo\x12A\n" +
	"\n" +
	"production\x18\x05 \x01(\v2\x1f.SC2APIProtocol.ProductionPanelH\x00R\n" +
	"productionB\a\n" +
	"\x05panel\"~\n" +
	"\fControlGroup\x12.\n" +
	"\x13control_group_index\x18\x01 \x01(\rR\x11controlGroupIndex\x12(\n" +
	"\x10leader_unit_type\x18\x02 \x01(\rR\x0eleaderUnitType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\x85\x03\n" +
	"\bUnitInfo\x12\x1b\n" +
	"\tunit_type\x18\x01 \x01(\rR\bunitType\x12'\n" +
	"\x0fplayer_relative\x18\x02 \x01(\rR\x0eplayerRelative\x12\x16\n" +
	"\x06health\x18\x03 \x01(\x05R\x06health\x12\x18\n" +
	"\ashields\x18\x04 \x01(\x05R\ashields\x12\x16\n" +
	"\x06energy\x18\x05 \x01(\x05R\x06energy\x122\n" +
	"\x15transport_slots_taken\x18\x06 \x01(\x05R\x13transportSlotsTaken\x12%\n" +
	"\x0ebuild_progress\x18\a \x01(\x02R\rbuildProgress\x12/\n" +
	"\x06add_on\x18\b \x01(\v2\x18.SC2APIProtocol.UnitInfoR\x05addOn\x12\x1d\n" +
	"\n" +
	"max_health\x18\t \x01(\x05R\tmaxHealth\x12\x1f\n" +
	"\vmax_shields\x18\n" +
	" \x01(\x05R\n" +
	"maxShields\x12\x1d\n" +
	"\n" +
	"max_energy\x18\v \x01(\x05R\tmaxEnergy\"\xe5\x01\n" +
	"\vSinglePanel\x12,\n" +
	"\x04unit\x18\x01 \x01(\v2\x18.SC2APIProtocol.UnitInfoR\x04unit\x120\n" +
	"\x14attack_upgrade_level\x18\x02 \x01(\x05R\x12attackUpgradeLevel\x12.\n" +
	"\x13armor_upgrade_level\x18\x03 \x01(\x05R\x11armorUpgradeLevel\x120\n" +
	"\x14shield_upgrade_level\x18\x04 \x01(\x05R\x12shieldUpgradeLevel\x12\x14\n" +
	"\x05buffs\x18\x05 \x03(\x05R\x05buffs\"<\n" +
	"\n" +
	"MultiPanel\x12.\n" +
	"\x05units\x18\x01 \x03(\v2\x18.SC2APIProtocol.UnitInfoR\x05units\"\x9d\x01\n" +
	"\n" +
	"CargoPanel\x12,\n" +
	"\x04unit\x18\x01 \x01(\v2\x18.SC2APIProtocol.UnitInfoR\x04unit\x128\n" +
	"\n" +
	"passengers\x18\x02 \x03(\v2\x18.SC2APIProtocol.UnitInfoR\n" +
	"passengers\x12'\n" +
	"\x0fslots_available\x18\x03 \x01(\x05R\x0eslotsAvailable\"Q\n" +
	"\tBuildItem\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\rR\tabilityId\x12%\n" +
	"\x0ebuild_progress\x18\x02 \x01(\x02R\rbuildProgress\"\xc0\x01\n" +
	"\x0fProductionPanel\x12,\n" +
	"\x04unit\x18\x01 \x01(\v2\x18.SC2APIProtocol.UnitInfoR\x04unit\x129\n" +
	"\vbuild_queue\x18\x02 \x03(\v2\x18.SC2APIProtocol.UnitInfoR\n" +
	"buildQueue\x12D\n" +
	"\x10production_queue\x18\x03 \x03(\v2\x19.SC2APIProtocol.BuildItemR\x0fproductionQueue\"\xdd\x05\n" +
	"\bActionUI\x12I\n" +
	"\rcontrol_group\x18\x01 \x01(\v2\".SC2APIProtocol.ActionControlGroupH\x00R\fcontrolGroup\x12C\n" +
	"\vselect_army\x18\x02 \x01(\v2 .SC2APIProtocol.ActionSelectArmyH\x00R\n" +
	"selectArmy\x12S\n" +
	"\x11select_warp_gates\x18\x03 \x01(\v2%.SC2APIProtocol.ActionSelectWarpGatesH\x00R\x0fselectWarpGates\x12F\n" +
	"\fselect_larva\x18\x04 \x01(\v2!.SC2APIProtocol.ActionSelectLarvaH\x00R\vselectLarva\x12V\n" +
	"\x12select_idle_worker\x18\x05 \x01(\v2&.SC2APIProtocol.ActionSelectIdleWorkerH\x00R\x10selectIdleWorker\x12C\n" +
	"\vmulti_panel\x18\x06 \x01(\v2 .SC2APIProtocol.ActionMultiPanelH\x00R\n" +
	"multiPanel\x12I\n" +
	"\vcargo_panel\x18\a \x01(\v2&.SC2APIProtocol.ActionCargoPanelUnloadH\x00R\n" +
	"cargoPanel\x12a\n" +
	"\x10production_panel\x18\b \x01(\v24.SC2APIProtocol.ActionProductionPanelRemoveFromQueueH\x00R\x0fproductionPanel\x12O\n" +
	"\x0ftoggle_autocast\x18\t \x01(\v2$.SC2APIProtocol.ActionToggleAutocastH\x00R\x0etoggleAutocastB\b\n" +
	"\x06action\"\xef\x01\n" +
	"\x12ActionControlGroup\x12M\n" +
	"\x06action\x18\x01 \x01(\x0e25.SC2APIProtocol.ActionControlGroup.ControlGroupActionR\x06action\x12.\n" +
	"\x13control_group_index\x18\x02 \x01(\rR\x11controlGroupIndex\"Z\n" +
	"\x12ControlGroupAction\x12\n" +
	"\n" +
	"\x06Recall\x10\x01\x12\a\n" +
	"\x03Set\x10\x02\x12\n" +
	"\n" +
	"\x06Append\x10\x03\x12\x0f\n" +
	"\vSetAndSteal\x10\x04\x12\x12\n" +
	"\x0eAppendAndSteal\x10\x05\"7\n" +
	"\x10ActionSelectArmy\x12#\n" +
	"\rselection_add\x18\x01 \x01(\bR\fselectionAdd\"<\n" +
	"\x15ActionSelectWarpGates\x12#\n" +
	"\rselection_add\x18\x01 \x01(\bR\fselectionAdd\"\x13\n" +
	"\x11ActionSelectLarva\"\x88\x01\n" +
	"\x16ActionSelectIdleWorker\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.SC2APIProtocol.ActionSelectIdleWorker.TypeR\x04type\"-\n" +
	"\x04Type\x12\a\n" +
	"\x03Set\x10\x01\x12\a\n" +
	"\x03Add\x10\x02\x12\a\n" +
	"\x03All\x10\x03\x12\n" +
	"\n" +
	"\x06AddAll\x10\x04\"\xc4\x01\n" +
	"\x10ActionMultiPanel\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.SC2APIProtocol.ActionMultiPanel.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x02 \x01(\x05R\tunitIndex\"V\n" +
	"\x04Type\x12\x10\n" +
	"\fSingleSelect\x10\x01\x12\x10\n" +
	"\fDeselectUnit\x10\x02\x12\x13\n" +
	"\x0fSelectAllOfType\x10\x03\x12\x15\n" +
	"\x11DeselectAllOfType\x10\x04\"7\n" +
	"\x16ActionCargoPanelUnload\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x05R\tunitIndex\"E\n" +
	"$ActionProductionPanelRemoveFromQueue\x12\x1d\n" +
	"\n" +
	"unit_index\x18\x01 \x01(\x05R\tunitIndex\"5\n" +
	"\x14ActionToggleAutocast\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId"

var (
	file_s2clientprotocol_ui_proto_rawDescOnce sync.Once
	file_s2clientprotocol_ui_proto_rawDescData []byte
)

func file_s2clientprotocol_ui_proto_rawDescGZIP() []byte {
	file_s2clientprotocol_ui_proto_rawDescOnce.Do(func() {
		file_s2clientprotocol_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2clientprotocol_ui_proto_rawDesc), len(file_s2clientprotocol_ui_proto_rawDesc)))
	})
	return file_s2clientprotocol_ui_proto_rawDescData
}

var file_s2clientprotocol_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_s2clientprotocol_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_s2clientprotocol_ui_proto_goTypes = []any{
	(ActionControlGroup_ControlGroupAction)(0),   // 0: SC2APIProtocol.ActionControlGroup.ControlGroupAction
	(ActionSelectIdleWorker_Type)(0),             // 1: SC2APIProtocol.ActionSelectIdleWorker.Type
	(ActionMultiPanel_Type)(0),                   // 2: SC2APIProtocol.ActionMultiPanel.Type
	(*ObservationUI)(nil),                        // 3: SC2APIProtocol.ObservationUI
	(*ControlGroup)(nil),                         // 4: SC2APIProtocol.ControlGroup
	(*UnitInfo)(nil),                             // 5: SC2APIProtocol.UnitInfo
	(*SinglePanel)(nil),                          // 6: SC2APIProtocol.SinglePanel
	(*MultiPanel)(nil),                           // 7: SC2APIProtocol.MultiPanel
	(*CargoPanel)(nil),                           // 8: SC2APIProtocol.CargoPanel
	(*BuildItem)(nil),                            // 9: SC2APIProtocol.BuildItem
	(*ProductionPanel)(nil),                      // 10: SC2APIProtocol.ProductionPanel
	(*ActionUI)(nil),                             // 11: SC2APIProtocol.ActionUI
	(*ActionControlGroup)(nil),                   // 12: SC2APIProtocol.ActionControlGroup
	(*ActionSelectArmy)(nil),                     // 13: SC2APIProtocol.ActionSelectArmy
	(*ActionSelectWarpGates)(nil),                // 14: SC2APIProtocol.ActionSelectWarpGates
	(*ActionSelectLarva)(nil),                    // 15: SC2APIProtocol.ActionSelectLarva
	(*ActionSelectIdleWorker)(nil),               // 16: SC2APIProtocol.ActionSelectIdleWorker
	(*ActionMultiPanel)(nil),                     // 17: SC2APIProtocol.ActionMultiPanel
	(*ActionCargoPanelUnload)(nil),               // 18: SC2APIProtocol.ActionCargoPanelUnload
	(*ActionProductionPanelRemoveFromQueue)(nil), // 19: SC2APIProtocol.ActionProductionPanelRemoveFromQueue
	(*ActionToggleAutocast)(nil),                 // 20: SC2APIProtocol.ActionToggleAutocast
}
var file_s2clientprotocol_ui_proto_depIdxs = []int32{
	4,  // 0: SC2APIProtocol.ObservationUI.groups:type_name -> SC2APIProtocol.ControlGroup
	6,  // 1: SC2APIProtocol.ObservationUI.single:type_name -> SC2APIProtocol.SinglePanel
	7,  // 2: SC2APIProtocol.ObservationUI.multi:type_name -> SC2APIProtocol.MultiPanel
	8,  // 3: SC2APIProtocol.ObservationUI.cargo:type_name -> SC2APIProtocol.CargoPanel
	10, // 4: SC2APIProtocol.ObservationUI.production:type_name -> SC2APIProtocol.ProductionPanel
	5,  // 5: SC2APIProtocol.UnitInfo.add_on:type_name -> SC2APIProtocol.UnitInfo
	5,  // 6: SC2APIProtocol.SinglePanel.unit:type_name -> SC2APIProtocol.UnitInfo
	5,  // 7: SC2APIProtocol.MultiPanel.units:type_name -> SC2APIProtocol.UnitInfo
	5,  // 8: SC2APIProtocol.CargoPanel.unit:type_name -> SC2APIProtocol.UnitInfo
	5,  // 9: SC2APIProtocol.CargoPanel.passengers:type_name -> SC2APIProtocol.UnitInfo
	5,  // 10: SC2APIProtocol.ProductionPanel.unit:type_name -> SC2APIProtocol.UnitInfo
	5,  // 11: SC2APIProtocol.ProductionPanel.build_queue:type_name -> SC2APIProtocol.UnitInfo
	9,  // 12: SC2APIProtocol.ProductionPanel.production_queue:type_name -> SC2APIProtocol.BuildItem
	12, // 13: SC2APIProtocol.ActionUI.control_group:type_name -> SC2APIProtocol.ActionControlGroup
	13, // 14: SC2APIProtocol.ActionUI.select_army:type_name -> SC2APIProtocol.ActionSelectArmy
	14, // 15: SC2APIProtocol.ActionUI.select_warp_gates:type_name -> SC2APIProtocol.ActionSelectWarpGates
	15, // 16: SC2APIProtocol.ActionUI.select_larva:type_name -> SC2APIProtocol.ActionSelectLarva
	16, // 17: SC2APIProtocol.ActionUI.select_idle_worker:type_name -> SC2APIProtocol.ActionSelectIdleWorker
	17, // 18: SC2APIProtocol.ActionUI.multi_panel:type_name -> SC2APIProtocol.ActionMultiPanel
	18, // 19: SC2APIProtocol.ActionUI.cargo_panel:type_name -> SC2APIProtocol.ActionCargoPanelUnload
	19, // 20: SC2APIProtocol.ActionUI.production_panel:type_name -> SC2APIProtocol.ActionProductionPanelRemoveFromQueue
	20, // 21: SC2APIProtocol.ActionUI.toggle_autocast:type_name -> SC2APIProtocol.ActionToggleAutocast
	0,  // 22: SC2APIProtocol.ActionControlGroup.action:type_name -> SC2APIProtocol.ActionControlGroup.ControlGroupAction
	1,  // 23: SC2APIProtocol.ActionSelectIdleWorker.type:type_name -> SC2APIProtocol.ActionSelectIdleWorker.Type
	2,  // 24: SC2APIProtocol.ActionMultiPanel.type:type_name -> SC2APIProtocol.ActionMultiPanel.Type
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_s2clientprotocol_ui_proto_init() }
func file_s2clientprotocol_ui_proto_init() {
	if File_s2clientprotocol_ui_proto != nil {
		return
	}
	file_s2clientprotocol_ui_proto_msgTypes[0].OneofWrappers = []any{
		(*ObservationUI_Single)(nil),
		(*ObservationUI_Multi)(nil),
		(*ObservationUI_Cargo)(nil),
		(*ObservationUI_Production)(nil),
	}
	file_s2clientprotocol_ui_proto_msgTypes[8].OneofWrappers = []any{
		(*ActionUI_ControlGroup)(nil),
		(*ActionUI_SelectArmy)(nil),
		(*ActionUI_SelectWarpGates)(nil),
		(*ActionUI_SelectLarva)(nil),
		(*ActionUI_SelectIdleWorker)(nil),
		(*ActionUI_MultiPanel)(nil),
		(*ActionUI_CargoPanel)(nil),
		(*ActionUI_ProductionPanel)(nil),
		(*ActionUI_ToggleAutocast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2clientprotocol_ui_proto_rawDesc), len(file_s2clientprotocol_ui_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2clientprotocol_ui_proto_goTypes,
		DependencyIndexes: file_s2clientprotocol_ui_proto_depIdxs,
		EnumInfos:         file_s2clientprotocol_ui_proto_enumTypes,
		MessageInfos:      file_s2clientprotocol_ui_proto_msgTypes,
	}.Build()
	File_s2clientprotocol_ui_proto = out.File
	file_s2clientprotocol_ui_proto_goTypes = nil
	file_s2clientprotocol_ui_proto_depIdxs = nil
}
